/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JDialog.java to edit this template
 */
package rekammedis;

import fungsi.koneksiDB;
import fungsi.sekuel;
import fungsi.validasi;
import java.awt.Color;
import java.awt.Component;
import java.awt.Dimension;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.util.Date;
import javax.swing.JTable;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableColumn;
import javax.swing.table.DefaultTableCellRenderer;

/**
 *
 * @author firka
 */
public class DlgCekSEP extends javax.swing.JDialog {
    private final DefaultTableModel tabMode;
     private JTable coloredTable;
    private Connection koneksi=koneksiDB.condb();
    private sekuel Sequel=new sekuel();
    private validasi Valid=new validasi();
    private PreparedStatement ps;
    private ResultSet rs;
    private int i=0;
    private Date tglSkrg = new Date();
    private String sqlNoSEP ="SELECT reg_periksa.no_rawat, reg_periksa.no_rkm_medis, reg_periksa.tgl_registrasi, IFNULL(bridging_sep.no_sep,'-- SEP KOSONG !! --') AS no_sep, IFNULL(bridging_sep.tglsep,'-') AS tgl_sep,"
        +"pasien.nm_pasien, reg_periksa.status_lanjut, IF(reg_periksa.kd_pj='BPJ','BPJS','-') AS jnsbyr, reg_periksa.stts,\n" +
        "IFNULL(bridging_sep.tglsep,'-') AS tgl_sep, \n" +
        "CASE WHEN bridging_sep.jnspelayanan = 1 THEN 'Ranap' WHEN bridging_sep.jnspelayanan = 2 THEN 'Ralan' ELSE '-- Tidak Diketahui --' END AS jenis_pelayanan\n" +
        "FROM reg_periksa LEFT OUTER JOIN bridging_sep ON reg_periksa.no_rawat = bridging_sep.no_rawat INNER JOIN pasien ON reg_periksa.no_rkm_medis = pasien.no_rkm_medis \n" +
        "WHERE reg_periksa.tgl_registrasi between ? AND ? AND bridging_sep.no_sep IS NULL AND reg_periksa.kd_pj = 'BPJ'";
    /**
     * Creates new form DlgCekSEP
     */
    public DlgCekSEP(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
         tabMode=new DefaultTableModel(null,new Object[]{
            "No.Rawat","No.RM","TglRegistrasi","No. SEP","Tgl SEP","Nama Pasien","Jns Layanan",
             "Jns Bayar","Status"
            
        }){
              @Override public boolean isCellEditable(int rowIndex, int colIndex){return false;}
        };
//        coloredTable = new JTable(tabMode);
        tbSEP.setDefaultRenderer(Object.class, new CustomTableCellRenderer());
        tbSEP.setModel(tabMode);
        //tbObat.setDefaultRenderer(Object.class, new WarnaTable(panelJudul.getBackground(),tbObat.getBackground()));
        tbSEP.setPreferredScrollableViewportSize(new Dimension(500,500));
        tbSEP.setAutoResizeMode(JTable.AUTO_RESIZE_OFF);
        tgl1.setDate(tglSkrg);
        tgl2.setDate(tglSkrg);             
        for (i = 0; i < 9; i++) {
            TableColumn column = tbSEP.getColumnModel().getColumn(i);
            if(i==0){
                column.setPreferredWidth(105);
            }else if(i==1){
                column.setPreferredWidth(70);
            }else if(i==2){
                column.setPreferredWidth(70);
            }else if(i==3){
                column.setPreferredWidth(150);
            }else if(i==4){
                column.setPreferredWidth(70);
            }else if(i==5){
                column.setPreferredWidth(180);
            }else if(i==6){
                column.setPreferredWidth(70);
            }else if(i==7){
                column.setPreferredWidth(65);
            }else if(i==8){
                column.setPreferredWidth(200);
            }
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        internalFrame1 = new widget.InternalFrame();
        panelBiasa1 = new widget.PanelBiasa();
        jScrollPane1 = new javax.swing.JScrollPane();
        tbSEP = new widget.Table();
        panelBiasa2 = new widget.PanelBiasa();
        tgl1 = new widget.Tanggal();
        label1 = new widget.Label();
        tgl2 = new widget.Tanggal();
        textBox1 = new widget.TextBox();
        cmbSEP = new widget.ComboBox();
        button1 = new widget.Button();
        panelisi21 = new widget.panelisi2();
        button3 = new widget.Button();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setUndecorated(true);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });

        internalFrame1.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createEtchedBorder(), "..:: Monitoring SEP ::..", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("sansserif", 0, 11))); // NOI18N
        internalFrame1.setLayout(new java.awt.BorderLayout());

        panelBiasa1.setLayout(new java.awt.BorderLayout());

        tbSEP.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {

            }
        ));
        jScrollPane1.setViewportView(tbSEP);

        panelBiasa1.add(jScrollPane1, java.awt.BorderLayout.CENTER);

        internalFrame1.add(panelBiasa1, java.awt.BorderLayout.CENTER);

        tgl1.setDate(new java.util.Date(1704933325000L));
        tgl1.setDisplayFormat("dd/MM/yyyy");
        panelBiasa2.add(tgl1);

        label1.setText("s/d");
        label1.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        panelBiasa2.add(label1);

        tgl2.setDate(new java.util.Date(1704933325000L));
        tgl2.setDisplayFormat("dd/MM/yyyy");
        panelBiasa2.add(tgl2);

        textBox1.setPreferredSize(new java.awt.Dimension(250, 24));
        panelBiasa2.add(textBox1);

        cmbSEP.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Belum SEP", "Semua" }));
        cmbSEP.setPreferredSize(new java.awt.Dimension(100, 24));
        panelBiasa2.add(cmbSEP);

        button1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/picture/accept.png"))); // NOI18N
        button1.setPreferredSize(new java.awt.Dimension(46, 32));
        button1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                button1ActionPerformed(evt);
            }
        });
        panelBiasa2.add(button1);

        panelisi21.setPreferredSize(new java.awt.Dimension(60, 25));

        javax.swing.GroupLayout panelisi21Layout = new javax.swing.GroupLayout(panelisi21);
        panelisi21.setLayout(panelisi21Layout);
        panelisi21Layout.setHorizontalGroup(
            panelisi21Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 58, Short.MAX_VALUE)
        );
        panelisi21Layout.setVerticalGroup(
            panelisi21Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 23, Short.MAX_VALUE)
        );

        panelBiasa2.add(panelisi21);

        button3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/picture/101.png"))); // NOI18N
        button3.setText("Keluar");
        button3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                button3ActionPerformed(evt);
            }
        });
        panelBiasa2.add(button3);

        internalFrame1.add(panelBiasa2, java.awt.BorderLayout.PAGE_END);

        getContentPane().add(internalFrame1, java.awt.BorderLayout.CENTER);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
       tampil();
    }//GEN-LAST:event_formWindowOpened

    private void button3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_button3ActionPerformed
        dispose();
    }//GEN-LAST:event_button3ActionPerformed

    private void button1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_button1ActionPerformed
//       if (cmbSEP.getSelectedIndex()==0){
//           tampilNoSEP();
//       }
        tampil();
    }//GEN-LAST:event_button1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(DlgCekSEP.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(DlgCekSEP.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(DlgCekSEP.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(DlgCekSEP.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                DlgCekSEP dialog = new DlgCekSEP(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                
                dialog.setVisible(true);
            }
        });
    }
    
        
     private class CustomTableCellRenderer extends DefaultTableCellRenderer {
        @Override
        public Component getTableCellRendererComponent(JTable table, Object value, boolean isSelected, boolean hasFocus, int row, int column) {
            Component cellComponent = super.getTableCellRendererComponent(table, value, isSelected, hasFocus, row, column);
            try{
            // Set background color for even rows
//            int rows = tbSEP.getSelectedRow();
            if (tbSEP.getValueAt(row,3).toString().equals("-")) {
                cellComponent.setBackground(Color.RED);
                cellComponent.setForeground(Color.white);    

            } else {
                cellComponent.setBackground(Color.WHITE);
                cellComponent.setForeground(Color.black);
            }
            
            }catch(Exception e){
                System.out.println("Error Render :"+e.getMessage());
            }
            return cellComponent;
        }
    }
    private void tampil(){
        try{
        ps=koneksi.prepareStatement("SELECT reg_periksa.no_rawat, reg_periksa.no_rkm_medis, reg_periksa.tgl_registrasi, IFNULL(bridging_sep.no_sep,'-') AS no_sep, IFNULL(bridging_sep.tglsep,'-') AS tgl_sep,"
        +"pasien.nm_pasien, reg_periksa.status_lanjut, IF(reg_periksa.kd_pj='BPJ','BPJS','-') AS jnsbyr, reg_periksa.stts,\n" +
        "IFNULL(bridging_sep.tglsep,'-') AS tgl_sep, \n" +
        "CASE WHEN bridging_sep.jnspelayanan = 1 THEN 'Ranap' WHEN bridging_sep.jnspelayanan = 2 THEN 'Ralan' ELSE '-- Tidak Diketahui --' END AS jenis_pelayanan\n" +
        "FROM reg_periksa LEFT OUTER JOIN bridging_sep ON reg_periksa.no_rawat = bridging_sep.no_rawat INNER JOIN pasien ON reg_periksa.no_rkm_medis = pasien.no_rkm_medis \n" +
        "WHERE reg_periksa.tgl_registrasi between ? AND ? AND reg_periksa.kd_pj = 'BPJ'");
        ps.setString(1, Valid.SetTgl(tgl1.getSelectedItem()+"")+" 00:00:00");
        ps.setString(2, Valid.SetTgl(tgl2.getSelectedItem()+"")+" 23:59:59");
        rs=ps.executeQuery();
        tabMode.setRowCount(0);
        while(rs.next()){
        tabMode.addRow(new String[]{
        rs.getString("no_rawat"),rs.getString("no_rkm_medis"),rs.getString("tgl_registrasi"),rs.getString("no_sep"),rs.getString("tgl_sep"),rs.getString("nm_pasien"),
        rs.getString("status_lanjut"),rs.getString("jnsbyr"),rs.getString("stts")        
        });}
        }catch(Exception e){
            System.out.println("Error : "+e.getMessage());
        }
    }
    private void tampilNoSEP(){
        try{
        ps=koneksi.prepareStatement(sqlNoSEP);
        ps.setString(1, Valid.SetTgl(tgl1.getSelectedItem()+"")+" 00:00:00");
        ps.setString(2, Valid.SetTgl(tgl2.getSelectedItem()+"")+" 23:59:59");
        rs=ps.executeQuery();
        tabMode.setRowCount(0);
        while(rs.next()){
        tabMode.addRow(new String[]{
        rs.getString("no_rawat"),rs.getString("no_rkm_medis"),rs.getString("tgl_registrasi"),rs.getString("no_sep"),rs.getString("tgl_sep"),rs.getString("nm_pasien"),
        rs.getString("status_lanjut"),rs.getString("jnsbyr"),rs.getString("stts")        
        });}
        }catch(Exception e){
            System.out.println("Error : "+e.getMessage());
        }
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private widget.Button button1;
    private widget.Button button3;
    private widget.ComboBox cmbSEP;
    private widget.InternalFrame internalFrame1;
    private javax.swing.JScrollPane jScrollPane1;
    private widget.Label label1;
    private widget.PanelBiasa panelBiasa1;
    private widget.PanelBiasa panelBiasa2;
    private widget.panelisi2 panelisi21;
    private widget.Table tbSEP;
    private widget.TextBox textBox1;
    private widget.Tanggal tgl1;
    private widget.Tanggal tgl2;
    // End of variables declaration//GEN-END:variables
}
