/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JDialog.java to edit this template
 */
package rekammedis;

import fungsi.koneksiDB;
import fungsi.sekuel;
import fungsi.validasi;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.text.SimpleDateFormat;
import java.util.Calendar;
import java.util.Enumeration;
import java.util.HashMap;
import java.util.Map;
import javax.swing.AbstractButton;
import javax.swing.ButtonGroup;
import javax.swing.JOptionPane;

/**
 *
 * @author firka
 */
public class DlgCatatPsikoterapi extends javax.swing.JDialog {
private validasi Valid = new validasi();
private sekuel sequel = new sekuel();
private Connection koneksi = koneksiDB.condb();
private PreparedStatement ps;
private String NULL;
private String dateStamp = new SimpleDateFormat("yyyy-MM-dd").format(Calendar.getInstance().getTime());
    /**
     * Creates new form DlgCatatPsikoterapi
     */
    public DlgCatatPsikoterapi(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        bg1 = new javax.swing.ButtonGroup();
        internalFrame1 = new widget.InternalFrame();
        panelGray1 = new widget.PanelGray();
        button1 = new widget.Button();
        button2 = new widget.Button();
        button3 = new widget.Button();
        button4 = new widget.Button();
        scrollPane1 = new widget.ScrollPane();
        panelGray4 = new widget.PanelGray();
        label1 = new widget.Label();
        txDiag2 = new widget.TextBox();
        label2 = new widget.Label();
        txDiag4 = new widget.TextBox();
        label3 = new widget.Label();
        txDiag3 = new widget.TextBox();
        txDiag1 = new widget.TextBox();
        label4 = new widget.Label();
        label8 = new widget.Label();
        jScrollPane1 = new javax.swing.JScrollPane();
        masalah = new widget.TextArea();
        label9 = new widget.Label();
        jScrollPane2 = new javax.swing.JScrollPane();
        prioritas = new widget.TextArea();
        label10 = new widget.Label();
        label11 = new widget.Label();
        kontrak1 = new javax.swing.JRadioButton();
        kontrak2 = new javax.swing.JRadioButton();
        waktu1 = new javax.swing.JRadioButton();
        waktu2 = new widget.TextBox();
        teknik1 = new javax.swing.JRadioButton();
        teknik2 = new javax.swing.JRadioButton();
        teknik3 = new javax.swing.JRadioButton();
        teknik4 = new widget.TextBox();
        label12 = new widget.Label();
        label13 = new widget.Label();
        tahapawal1 = new javax.swing.JRadioButton();
        tahapawal3 = new javax.swing.JRadioButton();
        tahapawal2 = new javax.swing.JRadioButton();
        tahapawal4 = new javax.swing.JRadioButton();
        label14 = new widget.Label();
        thptgh2 = new javax.swing.JRadioButton();
        thptgh1 = new javax.swing.JRadioButton();
        label15 = new widget.Label();
        label16 = new widget.Label();
        label17 = new widget.Label();
        tahaptgh1 = new javax.swing.JRadioButton();
        tahaptgh2 = new javax.swing.JRadioButton();
        tahaptgh6 = new javax.swing.JRadioButton();
        tahaptgh5 = new javax.swing.JRadioButton();
        tahaptgh3 = new javax.swing.JRadioButton();
        tahaptgh7 = new javax.swing.JRadioButton();
        tahaptgh4 = new javax.swing.JRadioButton();
        cbt_a = new widget.TextBox();
        label18 = new widget.Label();
        label19 = new widget.Label();
        cbt_b = new widget.TextBox();
        cbt_c = new widget.TextBox();
        label20 = new widget.Label();
        label5 = new widget.Label();
        txNoRwt = new widget.TextBox();
        label6 = new widget.Label();
        txnmPas = new widget.TextBox();
        label7 = new widget.Label();
        label21 = new widget.Label();
        label22 = new widget.Label();
        label23 = new widget.Label();
        cbt_f = new widget.TextBox();
        cbt_e = new widget.TextBox();
        cbt_d = new widget.TextBox();
        label24 = new widget.Label();
        tahapakhir1 = new javax.swing.JRadioButton();
        tahapakhir2 = new javax.swing.JRadioButton();
        tahapakhir3 = new javax.swing.JRadioButton();
        label25 = new widget.Label();
        jScrollPane3 = new javax.swing.JScrollPane();
        rencana = new widget.TextArea();
        txNoRM = new widget.TextBox();
        label26 = new widget.Label();
        tahaptgh8 = new javax.swing.JRadioButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setUndecorated(true);

        internalFrame1.setBorder(null);
        internalFrame1.setLayout(new java.awt.BorderLayout());

        button1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/picture/095.png"))); // NOI18N
        button1.setText("Simpan");
        button1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                button1ActionPerformed(evt);
            }
        });
        panelGray1.add(button1);

        button2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/picture/PrinterSettings.png"))); // NOI18N
        button2.setText("Cetak");
        button2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                button2ActionPerformed(evt);
            }
        });
        panelGray1.add(button2);

        button3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/picture/edit_f2.png"))); // NOI18N
        button3.setText("Ganti");
        panelGray1.add(button3);

        button4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/picture/101.png"))); // NOI18N
        button4.setText("Keluar");
        button4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                button4ActionPerformed(evt);
            }
        });
        panelGray1.add(button4);

        internalFrame1.add(panelGray1, java.awt.BorderLayout.PAGE_END);

        scrollPane1.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createEtchedBorder(), "..:: Formulir Pencatatan Psikoterapi ::..", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("sansserif", 0, 11))); // NOI18N
        scrollPane1.setHorizontalScrollBarPolicy(javax.swing.ScrollPaneConstants.HORIZONTAL_SCROLLBAR_ALWAYS);

        label1.setText("Aksis I");
        label1.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N

        txDiag2.setText("-");

        label2.setText("Aksis II");
        label2.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N

        txDiag4.setText("GRAF");
        txDiag4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txDiag4ActionPerformed(evt);
            }
        });

        label3.setText("Aksis II");
        label3.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N

        txDiag3.setText("GRAF");

        txDiag1.setText("-");

        label4.setText("Aksis II");
        label4.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N

        label8.setText("II. PERMASALAH YANG DITEMUKAN (IDENTIFIKASI MASALAH)");
        label8.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N

        masalah.setColumns(20);
        masalah.setRows(5);
        masalah.setText("-");
        jScrollPane1.setViewportView(masalah);

        label9.setText("Prioritas Masalah :");
        label9.setFont(new java.awt.Font("SansSerif", 0, 12)); // NOI18N

        prioritas.setColumns(20);
        prioritas.setRows(5);
        prioritas.setText("-");
        jScrollPane2.setViewportView(prioritas);

        label10.setText("I. DIAGNOSIS KERJA");
        label10.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N

        label11.setText("III. KONTRAK TERAPI");
        label11.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N

        kontrak1.setBackground(new java.awt.Color(255, 255, 255));
        kontrak1.setText("Psikoterapi Individual");

        kontrak2.setBackground(new java.awt.Color(255, 255, 255));
        kontrak2.setText("Psikoterapi Kelompok");

        waktu1.setBackground(new java.awt.Color(255, 255, 255));
        waktu1.setText("(50 Menit/Minggu)");

        waktu2.setText("-");

        teknik1.setBackground(new java.awt.Color(255, 255, 255));
        teknik1.setText("Psikoterapi Supportif");

        teknik2.setBackground(new java.awt.Color(255, 255, 255));
        teknik2.setText("Psikoterapi Psikoanalisis/Psikodinamis");

        teknik3.setBackground(new java.awt.Color(255, 255, 255));
        teknik3.setText("Psikoterapi Spesifik");

        teknik4.setText("-");

        label12.setText("Psikoterapi Lainnya...");
        label12.setFont(new java.awt.Font("SansSerif", 0, 12)); // NOI18N

        label13.setText("IV. TAHAPAN PSIKOTERAPI");
        label13.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N

        tahapawal1.setBackground(new java.awt.Color(255, 255, 255));
        bg1.add(tahapawal1);
        tahapawal1.setText("Membangun hubungan terapi");

        tahapawal3.setBackground(new java.awt.Color(255, 255, 255));
        bg1.add(tahapawal3);
        tahapawal3.setText("Memperjelas mendefinisikan Masalah");

        tahapawal2.setBackground(new java.awt.Color(255, 255, 255));
        bg1.add(tahapawal2);
        tahapawal2.setText("Negosiasi Kontrak");

        tahapawal4.setBackground(new java.awt.Color(255, 255, 255));
        bg1.add(tahapawal4);
        tahapawal4.setText("Membuat penafsiran & penjajakan");

        label14.setText("1. Tahap awal terapi");
        label14.setFont(new java.awt.Font("SansSerif", 0, 12)); // NOI18N

        thptgh2.setBackground(new java.awt.Color(255, 255, 255));
        thptgh2.setText("Menjaga hubungan terapi selalu terpelihara");

        thptgh1.setBackground(new java.awt.Color(255, 255, 255));
        thptgh1.setText("Penjelajahan masalah pasien / klien");

        label15.setText("2. Tahap Pertengahan");
        label15.setFont(new java.awt.Font("SansSerif", 0, 12)); // NOI18N

        label16.setText("CBT");
        label16.setFont(new java.awt.Font("SansSerif", 0, 12)); // NOI18N

        label17.setText("Teknik");
        label17.setFont(new java.awt.Font("SansSerif", 0, 12)); // NOI18N

        tahaptgh1.setBackground(new java.awt.Color(255, 255, 255));
        tahaptgh1.setText("Ventilasi dan Katarsis");

        tahaptgh2.setBackground(new java.awt.Color(255, 255, 255));
        tahaptgh2.setText("Persuasi");

        tahaptgh6.setBackground(new java.awt.Color(255, 255, 255));
        tahaptgh6.setText("Asosiasi bebas");

        tahaptgh5.setBackground(new java.awt.Color(255, 255, 255));
        tahaptgh5.setText("Reassurance/Penjamin Kembali");

        tahaptgh3.setBackground(new java.awt.Color(255, 255, 255));
        tahaptgh3.setText("Interpretasi");

        tahaptgh7.setBackground(new java.awt.Color(255, 255, 255));
        tahaptgh7.setText("Konfrontasi");

        tahaptgh4.setBackground(new java.awt.Color(255, 255, 255));
        tahaptgh4.setText("Intervensi khusus");

        cbt_a.setText("-");

        label18.setText("Activiting Event");
        label18.setFont(new java.awt.Font("SansSerif", 0, 12)); // NOI18N

        label19.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        label19.setText("Belief");
        label19.setFont(new java.awt.Font("SansSerif", 0, 12)); // NOI18N

        cbt_b.setText("-");

        cbt_c.setText("-");

        label20.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        label20.setText("Consequence");
        label20.setFont(new java.awt.Font("SansSerif", 0, 12)); // NOI18N

        label5.setText("No RM");
        label5.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N

        label6.setText("Nama Pasien");
        label6.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N

        label7.setText("No Rawat");
        label7.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N

        label21.setText("Dispute");
        label21.setFont(new java.awt.Font("SansSerif", 0, 12)); // NOI18N

        label22.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        label22.setText("Efek Baru");
        label22.setFont(new java.awt.Font("SansSerif", 0, 12)); // NOI18N

        label23.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        label23.setText("Further Action");
        label23.setFont(new java.awt.Font("SansSerif", 0, 12)); // NOI18N

        cbt_f.setText("-");

        cbt_e.setText("-");
        cbt_e.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbt_eActionPerformed(evt);
            }
        });

        cbt_d.setText("-");

        label24.setText("3. Tahap akhir terapi");
        label24.setFont(new java.awt.Font("SansSerif", 0, 12)); // NOI18N

        tahapakhir1.setBackground(new java.awt.Color(255, 255, 255));
        tahapakhir1.setText("Memutuskan perubahan sikap & perilaku yang memadai");

        tahapakhir2.setBackground(new java.awt.Color(255, 255, 255));
        tahapakhir2.setText("Mengakhiri hubungan terapi");

        tahapakhir3.setBackground(new java.awt.Color(255, 255, 255));
        tahapakhir3.setText("Melaksanakan pembahasan perilaku");

        label25.setText("V. RENCANA TINDAK LANJUT");
        label25.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N

        rencana.setColumns(20);
        rencana.setRows(5);
        rencana.setText("-");
        jScrollPane3.setViewportView(rencana);

        label26.setText("Waktu Lainnya...");
        label26.setFont(new java.awt.Font("SansSerif", 0, 12)); // NOI18N

        tahaptgh8.setBackground(new java.awt.Color(255, 255, 255));
        tahaptgh8.setText("Sugesti");

        javax.swing.GroupLayout panelGray4Layout = new javax.swing.GroupLayout(panelGray4);
        panelGray4.setLayout(panelGray4Layout);
        panelGray4Layout.setHorizontalGroup(
            panelGray4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelGray4Layout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addGroup(panelGray4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panelGray4Layout.createSequentialGroup()
                        .addGap(19, 19, 19)
                        .addGroup(panelGray4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(panelGray4Layout.createSequentialGroup()
                                .addGroup(panelGray4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(label14, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(panelGray4Layout.createSequentialGroup()
                                        .addGroup(panelGray4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(tahapawal1)
                                            .addComponent(tahapawal2))
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addGroup(panelGray4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(tahapawal4)
                                            .addComponent(tahapawal3))))
                                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addGroup(panelGray4Layout.createSequentialGroup()
                                .addGroup(panelGray4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(label15, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(panelGray4Layout.createSequentialGroup()
                                        .addComponent(thptgh1)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(thptgh2))
                                    .addGroup(panelGray4Layout.createSequentialGroup()
                                        .addGap(22, 22, 22)
                                        .addGroup(panelGray4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(label17, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addGroup(panelGray4Layout.createSequentialGroup()
                                                .addGap(6, 6, 6)
                                                .addGroup(panelGray4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                    .addComponent(tahaptgh1)
                                                    .addComponent(tahaptgh2)
                                                    .addComponent(tahaptgh3)
                                                    .addComponent(tahaptgh4))
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                                .addGroup(panelGray4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                    .addComponent(tahaptgh7)
                                                    .addComponent(tahaptgh5)
                                                    .addComponent(tahaptgh6)
                                                    .addComponent(tahaptgh8)))))
                                    .addComponent(label24, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(panelGray4Layout.createSequentialGroup()
                                        .addGap(17, 17, 17)
                                        .addGroup(panelGray4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(tahapakhir2)
                                            .addComponent(tahapakhir3)
                                            .addGroup(panelGray4Layout.createSequentialGroup()
                                                .addComponent(tahapakhir1)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 185, Short.MAX_VALUE)
                                                .addGroup(panelGray4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                                    .addGroup(panelGray4Layout.createSequentialGroup()
                                                        .addGroup(panelGray4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                            .addComponent(label21, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                            .addComponent(label23, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                            .addComponent(label22, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                                        .addGap(18, 18, 18)
                                                        .addGroup(panelGray4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                            .addGroup(panelGray4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                                .addComponent(cbt_e, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 421, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                                .addComponent(cbt_f, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 421, javax.swing.GroupLayout.PREFERRED_SIZE))
                                                            .addComponent(cbt_d, javax.swing.GroupLayout.PREFERRED_SIZE, 421, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                                    .addGroup(panelGray4Layout.createSequentialGroup()
                                                        .addGroup(panelGray4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                            .addComponent(label18, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                            .addComponent(label20, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                            .addComponent(label19, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                            .addComponent(label16, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                                        .addGroup(panelGray4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                            .addGroup(panelGray4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                                .addComponent(cbt_b, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 421, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                                .addComponent(cbt_c, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 421, javax.swing.GroupLayout.PREFERRED_SIZE))
                                                            .addComponent(cbt_a, javax.swing.GroupLayout.PREFERRED_SIZE, 421, javax.swing.GroupLayout.PREFERRED_SIZE))))))))
                                .addGap(68, 68, 68))))
                    .addGroup(panelGray4Layout.createSequentialGroup()
                        .addGroup(panelGray4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(panelGray4Layout.createSequentialGroup()
                                .addGap(6, 6, 6)
                                .addComponent(jScrollPane3))
                            .addGroup(panelGray4Layout.createSequentialGroup()
                                .addGroup(panelGray4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(label13, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(label11, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(panelGray4Layout.createSequentialGroup()
                                        .addGap(21, 21, 21)
                                        .addGroup(panelGray4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addGroup(panelGray4Layout.createSequentialGroup()
                                                .addComponent(teknik1)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                                .addComponent(teknik2)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                                .addComponent(teknik3))
                                            .addGroup(panelGray4Layout.createSequentialGroup()
                                                .addComponent(label12, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addComponent(teknik4, javax.swing.GroupLayout.PREFERRED_SIZE, 258, javax.swing.GroupLayout.PREFERRED_SIZE))
                                            .addGroup(panelGray4Layout.createSequentialGroup()
                                                .addGroup(panelGray4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                    .addComponent(kontrak1)
                                                    .addComponent(waktu1))
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                                .addGroup(panelGray4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                    .addComponent(kontrak2)
                                                    .addGroup(panelGray4Layout.createSequentialGroup()
                                                        .addComponent(label26, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                        .addGap(2, 2, 2)
                                                        .addComponent(waktu2, javax.swing.GroupLayout.PREFERRED_SIZE, 258, javax.swing.GroupLayout.PREFERRED_SIZE))))))
                                    .addGroup(panelGray4Layout.createSequentialGroup()
                                        .addGap(14, 14, 14)
                                        .addGroup(panelGray4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                            .addComponent(label4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addGroup(panelGray4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                                .addComponent(txDiag3, javax.swing.GroupLayout.PREFERRED_SIZE, 139, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addGroup(panelGray4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                                    .addGroup(panelGray4Layout.createSequentialGroup()
                                                        .addComponent(label1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                                        .addComponent(txDiag1, javax.swing.GroupLayout.PREFERRED_SIZE, 138, javax.swing.GroupLayout.PREFERRED_SIZE))
                                                    .addGroup(panelGray4Layout.createSequentialGroup()
                                                        .addComponent(label3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                        .addComponent(txDiag2, javax.swing.GroupLayout.PREFERRED_SIZE, 139, javax.swing.GroupLayout.PREFERRED_SIZE))))
                                            .addGroup(panelGray4Layout.createSequentialGroup()
                                                .addComponent(label2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addComponent(txDiag4, javax.swing.GroupLayout.PREFERRED_SIZE, 139, javax.swing.GroupLayout.PREFERRED_SIZE))))
                                    .addGroup(panelGray4Layout.createSequentialGroup()
                                        .addComponent(label7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(txNoRwt, javax.swing.GroupLayout.PREFERRED_SIZE, 143, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(18, 18, 18)
                                        .addComponent(label5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(txNoRM, javax.swing.GroupLayout.PREFERRED_SIZE, 143, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(18, 18, 18)
                                        .addComponent(label6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(txnmPas, javax.swing.GroupLayout.PREFERRED_SIZE, 243, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addComponent(label10, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(panelGray4Layout.createSequentialGroup()
                                        .addGroup(panelGray4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(label8, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addGroup(panelGray4Layout.createSequentialGroup()
                                                .addGap(20, 20, 20)
                                                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 431, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                        .addGap(18, 18, 18)
                                        .addGroup(panelGray4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(label9, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 447, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                    .addComponent(label25, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(0, 0, Short.MAX_VALUE)))
                        .addContainerGap())))
        );
        panelGray4Layout.setVerticalGroup(
            panelGray4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelGray4Layout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addGroup(panelGray4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(label7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txNoRwt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(label5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txNoRM, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txnmPas, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(label6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(30, 30, 30)
                .addComponent(label10, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(7, 7, 7)
                .addGroup(panelGray4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(label1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txDiag1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(panelGray4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(label3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txDiag2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(panelGray4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(label4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txDiag3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(panelGray4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(label2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txDiag4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(panelGray4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(panelGray4Layout.createSequentialGroup()
                        .addComponent(label8, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 102, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(panelGray4Layout.createSequentialGroup()
                        .addComponent(label9, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 102, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(18, 18, 18)
                .addComponent(label11, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(panelGray4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(kontrak1)
                    .addComponent(kontrak2))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(panelGray4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(waktu1)
                    .addComponent(waktu2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(label26, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(panelGray4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(teknik1)
                    .addComponent(teknik2)
                    .addComponent(teknik3))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(panelGray4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(teknik4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(label12, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(label13, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(label14, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(panelGray4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(tahapawal1)
                    .addComponent(tahapawal3))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(panelGray4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(tahapawal2)
                    .addComponent(tahapawal4))
                .addGap(18, 18, 18)
                .addComponent(label15, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(1, 1, 1)
                .addGroup(panelGray4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panelGray4Layout.createSequentialGroup()
                        .addGroup(panelGray4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(thptgh1)
                            .addComponent(thptgh2))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(label17, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(panelGray4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(tahaptgh1)
                            .addComponent(tahaptgh5))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(panelGray4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(tahaptgh2)
                            .addComponent(tahaptgh6))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(panelGray4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(tahaptgh7)
                            .addComponent(tahaptgh3))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(panelGray4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(tahaptgh4)
                            .addComponent(tahaptgh8))
                        .addGap(18, 18, 18)
                        .addComponent(label24, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(tahapakhir1))
                    .addGroup(panelGray4Layout.createSequentialGroup()
                        .addComponent(label16, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(panelGray4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(cbt_a, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(label18, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(panelGray4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(cbt_b, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(label19, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(panelGray4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(cbt_c, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(label20, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(panelGray4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(cbt_d, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(label21, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(panelGray4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(cbt_e, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(label22, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(panelGray4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(cbt_f, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(label23, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(tahapakhir2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(tahapakhir3)
                .addGap(18, 18, 18)
                .addComponent(label25, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        scrollPane1.setViewportView(panelGray4);

        internalFrame1.add(scrollPane1, java.awt.BorderLayout.CENTER);

        getContentPane().add(internalFrame1, java.awt.BorderLayout.CENTER);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    public void setNo(String noRw, String nmPasien, String noRM, String Diag){
        txNoRwt.setText(noRw);
        txnmPas.setText(nmPasien);
        txNoRM.setText(noRM);
        txDiag1.setText(Diag);
    }
    
    private void txDiag4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txDiag4ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txDiag4ActionPerformed

    private void button4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_button4ActionPerformed
        dispose();
    }//GEN-LAST:event_button4ActionPerformed

    private void cbt_eActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbt_eActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cbt_eActionPerformed

    private void cek_list(){
        if(kontrak1.isSelected()==true){
            kontrak1.getText();
        }else{
            kontrak1.setText("-");
        }
        if(kontrak2.isSelected()==true){
            kontrak2.getText();
        }else{
            kontrak2.setText("-");
        }
        if(waktu1.isSelected()==true){
            waktu1.getText();
        }else{
            waktu1.setText("-");
        }
        if(teknik1.isSelected()==true){
            teknik1.getText();
        }else{
            teknik1.setText("-");
        }
        if(teknik2.isSelected()==true){
            teknik2.getText();
        }else{
            teknik2.setText("-");
        }
        if(teknik3.isSelected()==true){
            teknik3.getText();
        }else{
            teknik3.setText("-");
        }
        if(tahapawal1.isSelected()==true){
            tahapawal1.getText();
        }else{
            tahapawal1.setText("-");
        }
        if(tahapawal2.isSelected()==true){
            tahapawal2.getText();
        }else{
            tahapawal2.setText("-");
        }
        if(tahapawal3.isSelected()==true){
            tahapawal3.getText();
        }else{
            tahapawal3.setText("-");
        }
        if(tahapawal4.isSelected()==true){
            tahapawal4.getText();
        }else{
            tahapawal4.setText("-");
        }
        if(thptgh1.isSelected()==true){
            thptgh1.getText();
        }else{
            thptgh1.setText("-");
        }
        if(thptgh2.isSelected()==true){
            thptgh2.getText();
        }else{
            thptgh2.setText("-");
        }
        if(tahaptgh1.isSelected()==true){
            tahaptgh1.getText();
        }else{
            tahaptgh1.setText("-");
        }
        if(tahaptgh2.isSelected()==true){
            tahaptgh2.getText();
        }else{
            tahaptgh2.setText("-");
        }
         if(tahaptgh3.isSelected()==true){
            tahaptgh3.getText();
        }else{
            tahaptgh3.setText("-");
        }
        if(tahaptgh4.isSelected()==true){
            tahaptgh4.getText();
        }else{
            tahaptgh4.setText("-");
        }
         if(tahaptgh5.isSelected()==true){
            tahaptgh5.getText();
        }else{
            tahaptgh5.setText("-");
        }
        if(tahaptgh6.isSelected()==true){
            tahaptgh6.getText();
        }else{
            tahaptgh6.setText("-");
        }
         if(tahaptgh7.isSelected()==true){
            tahaptgh7.getText();
        }else{
            tahaptgh7.setText("-");
        }
        if(tahaptgh8.isSelected()==true){
            tahaptgh8.getText();
        }else{
            tahaptgh8.setText("-");
        }
        if(tahapakhir1.isSelected()==true){
            tahapakhir1.getText();
        }else{
            tahapakhir1.setText("-");
        }
        if(tahapakhir2.isSelected()==true){
            tahapakhir2.getText();
        }else{
            tahapakhir2.setText("-");
        }
        if(tahapakhir3.isSelected()==true){
            tahapakhir3.getText();
        }else{
            tahapakhir3.setText("-");
        }
    }
    
    private void button1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_button1ActionPerformed
     try {
        cek_list(); 
        ps = koneksi.prepareStatement("insert into pencatatan_psikoterapi value (?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?)");
        ps.setString(1, txNoRwt.getText());
        ps.setString(2, dateStamp);
        ps.setString(3, txDiag1.getText());
        ps.setString(4, txDiag2.getText());
        ps.setString(5, txDiag3.getText());
        ps.setString(6, txDiag4.getText());
        ps.setString(7, masalah.getText());
        ps.setString(8, prioritas.getText());
        ps.setString(9, kontrak1.getText());
        ps.setString(10, kontrak2.getText());
        ps.setString(11, waktu1.getText());
        ps.setString(12, waktu2.getText());
        ps.setString(13, teknik1.getText());
        ps.setString(14, teknik2.getText());
        ps.setString(15, teknik3.getText());
        ps.setString(16, teknik4.getText());
        ps.setString(17, tahapawal1.getText());
        ps.setString(18, thptgh1.getText());
        ps.setString(19, thptgh2.getText());
        ps.setString(20, tahaptgh1.getText());
        ps.setString(21, tahaptgh2.getText());
        ps.setString(22, tahaptgh3.getText());
        ps.setString(23, tahaptgh4.getText());
        ps.setString(24, tahaptgh5.getText());
        ps.setString(25, tahaptgh6.getText());
        ps.setString(26, tahaptgh7.getText());
        ps.setString(27, tahaptgh8.getText());
        ps.setString(28, cbt_a.getText());
        ps.setString(29, cbt_b.getText());
        ps.setString(30, cbt_c.getText());
        ps.setString(31, cbt_d.getText());
        ps.setString(32, cbt_e.getText());
        ps.setString(33, cbt_f.getText());
        ps.setString(34, tahapakhir1.getText());
        ps.setString(35, tahapakhir2.getText());
        ps.setString(36, tahapakhir3.getText());
        ps.setString(37, rencana.getText());
        ps.setString(38, NULL);
        ps.executeUpdate();
         JOptionPane.showMessageDialog(null, "Tersimpan");
     }catch(Exception e){
         System.out.println("Error : "+e.getMessage());
     }
    }//GEN-LAST:event_button1ActionPerformed

    private void button2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_button2ActionPerformed
        Map<String, Object> param = new HashMap<>();
        param.put("logo",sequel.cariGambar("select setting.logo from setting"));
        Valid.MyReportqry("catatan_psikoterapi.jasper", "report", "::[ Laporan Pencatatan Psikoterapi ]::", "SELECT reg_periksa.no_rkm_medis, pasien.nm_pasien, dokter.nm_dokter, pencatatan_psikoterapi.* FROM reg_periksa" +
    " INNER JOIN pasien ON reg_periksa.no_rkm_medis = pasien.no_rkm_medis "
                + "INNER JOIN dokter ON reg_periksa.kd_dokter = dokter.kd_dokter " 
                + "INNER JOIN pencatatan_psikoterapi ON pencatatan_psikoterapi.no_rawat = reg_periksa.no_rawat where pencatatan_psikoterapi.no_rawat='"+txNoRwt.getText()+"'",param);
    }//GEN-LAST:event_button2ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(DlgCatatPsikoterapi.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(DlgCatatPsikoterapi.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(DlgCatatPsikoterapi.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(DlgCatatPsikoterapi.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                DlgCatatPsikoterapi dialog = new DlgCatatPsikoterapi(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup bg1;
    private widget.Button button1;
    private widget.Button button2;
    private widget.Button button3;
    private widget.Button button4;
    private widget.TextBox cbt_a;
    private widget.TextBox cbt_b;
    private widget.TextBox cbt_c;
    private widget.TextBox cbt_d;
    private widget.TextBox cbt_e;
    private widget.TextBox cbt_f;
    private widget.InternalFrame internalFrame1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JRadioButton kontrak1;
    private javax.swing.JRadioButton kontrak2;
    private widget.Label label1;
    private widget.Label label10;
    private widget.Label label11;
    private widget.Label label12;
    private widget.Label label13;
    private widget.Label label14;
    private widget.Label label15;
    private widget.Label label16;
    private widget.Label label17;
    private widget.Label label18;
    private widget.Label label19;
    private widget.Label label2;
    private widget.Label label20;
    private widget.Label label21;
    private widget.Label label22;
    private widget.Label label23;
    private widget.Label label24;
    private widget.Label label25;
    private widget.Label label26;
    private widget.Label label3;
    private widget.Label label4;
    private widget.Label label5;
    private widget.Label label6;
    private widget.Label label7;
    private widget.Label label8;
    private widget.Label label9;
    private widget.TextArea masalah;
    private widget.PanelGray panelGray1;
    private widget.PanelGray panelGray4;
    private widget.TextArea prioritas;
    private widget.TextArea rencana;
    private widget.ScrollPane scrollPane1;
    private javax.swing.JRadioButton tahapakhir1;
    private javax.swing.JRadioButton tahapakhir2;
    private javax.swing.JRadioButton tahapakhir3;
    private javax.swing.JRadioButton tahapawal1;
    private javax.swing.JRadioButton tahapawal2;
    private javax.swing.JRadioButton tahapawal3;
    private javax.swing.JRadioButton tahapawal4;
    private javax.swing.JRadioButton tahaptgh1;
    private javax.swing.JRadioButton tahaptgh2;
    private javax.swing.JRadioButton tahaptgh3;
    private javax.swing.JRadioButton tahaptgh4;
    private javax.swing.JRadioButton tahaptgh5;
    private javax.swing.JRadioButton tahaptgh6;
    private javax.swing.JRadioButton tahaptgh7;
    private javax.swing.JRadioButton tahaptgh8;
    private javax.swing.JRadioButton teknik1;
    private javax.swing.JRadioButton teknik2;
    private javax.swing.JRadioButton teknik3;
    private widget.TextBox teknik4;
    private javax.swing.JRadioButton thptgh1;
    private javax.swing.JRadioButton thptgh2;
    private widget.TextBox txDiag1;
    private widget.TextBox txDiag2;
    private widget.TextBox txDiag3;
    private widget.TextBox txDiag4;
    private widget.TextBox txNoRM;
    private widget.TextBox txNoRwt;
    private widget.TextBox txnmPas;
    private javax.swing.JRadioButton waktu1;
    private widget.TextBox waktu2;
    // End of variables declaration//GEN-END:variables
}
