/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JDialog.java to edit this template
 */
package rekammedis;

import fungsi.koneksiDB;
import fungsi.sekuel;
import fungsi.validasi;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.text.SimpleDateFormat;
import java.util.Calendar;
import javax.swing.JOptionPane;

/**
 *
 * @author firka
 */
public class DlgCatatPsikoterapi extends javax.swing.JDialog {
private validasi Valid = new validasi();
private sekuel sequel = new sekuel();
private Connection koneksi = koneksiDB.condb();
private PreparedStatement ps;
private String NULL;
private String dateStamp = new SimpleDateFormat("yyyy-MM-dd").format(Calendar.getInstance().getTime());
    /**
     * Creates new form DlgCatatPsikoterapi
     */
    public DlgCatatPsikoterapi(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        bg1 = new javax.swing.ButtonGroup();
        internalFrame1 = new widget.InternalFrame();
        panelGray1 = new widget.PanelGray();
        button1 = new widget.Button();
        button2 = new widget.Button();
        button3 = new widget.Button();
        button4 = new widget.Button();
        scrollPane1 = new widget.ScrollPane();
        panelGray4 = new widget.PanelGray();
        label1 = new widget.Label();
        txDiag2 = new widget.TextBox();
        label2 = new widget.Label();
        txDiag4 = new widget.TextBox();
        label3 = new widget.Label();
        txDiag3 = new widget.TextBox();
        txDiag1 = new widget.TextBox();
        label4 = new widget.Label();
        label8 = new widget.Label();
        jScrollPane1 = new javax.swing.JScrollPane();
        txmasalah1 = new widget.TextArea();
        label9 = new widget.Label();
        jScrollPane2 = new javax.swing.JScrollPane();
        txmasalah2 = new widget.TextArea();
        label10 = new widget.Label();
        label11 = new widget.Label();
        terapi1 = new javax.swing.JRadioButton();
        terapi4 = new javax.swing.JRadioButton();
        terapi2 = new javax.swing.JRadioButton();
        terapi5 = new widget.TextBox();
        terapi3 = new javax.swing.JRadioButton();
        terapi6 = new javax.swing.JRadioButton();
        terapi7 = new javax.swing.JRadioButton();
        terapi8 = new widget.TextBox();
        label12 = new widget.Label();
        label13 = new widget.Label();
        tahapawal1 = new javax.swing.JRadioButton();
        tahapawal3 = new javax.swing.JRadioButton();
        tahapawal2 = new javax.swing.JRadioButton();
        tahapawal4 = new javax.swing.JRadioButton();
        label14 = new widget.Label();
        tahap6 = new javax.swing.JRadioButton();
        tahap5 = new javax.swing.JRadioButton();
        label15 = new widget.Label();
        label16 = new widget.Label();
        label17 = new widget.Label();
        tahaptgh1 = new javax.swing.JRadioButton();
        tahaptgh2 = new javax.swing.JRadioButton();
        tahaptgh6 = new javax.swing.JRadioButton();
        tahaptgh5 = new javax.swing.JRadioButton();
        tahaptgh3 = new javax.swing.JRadioButton();
        tahaptgh7 = new javax.swing.JRadioButton();
        tahaptgh4 = new javax.swing.JRadioButton();
        cbt_a = new widget.TextBox();
        label18 = new widget.Label();
        label19 = new widget.Label();
        cbt_b = new widget.TextBox();
        cbt_c = new widget.TextBox();
        label20 = new widget.Label();
        label5 = new widget.Label();
        txNoRwt = new widget.TextBox();
        label6 = new widget.Label();
        txnmPas = new widget.TextBox();
        label7 = new widget.Label();
        label21 = new widget.Label();
        label22 = new widget.Label();
        label23 = new widget.Label();
        cbt_f = new widget.TextBox();
        cbt_e = new widget.TextBox();
        cbt_d = new widget.TextBox();
        label24 = new widget.Label();
        jRadioButton15 = new javax.swing.JRadioButton();
        jRadioButton24 = new javax.swing.JRadioButton();
        jRadioButton25 = new javax.swing.JRadioButton();
        label25 = new widget.Label();
        jScrollPane3 = new javax.swing.JScrollPane();
        textArea3 = new widget.TextArea();
        txNoRM = new widget.TextBox();
        label26 = new widget.Label();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setUndecorated(true);

        internalFrame1.setBorder(null);
        internalFrame1.setLayout(new java.awt.BorderLayout());

        button1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/picture/095.png"))); // NOI18N
        button1.setText("Simpan");
        button1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                button1ActionPerformed(evt);
            }
        });
        panelGray1.add(button1);

        button2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/picture/PrinterSettings.png"))); // NOI18N
        button2.setText("Cetak");
        panelGray1.add(button2);

        button3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/picture/011.png"))); // NOI18N
        button3.setText("button3");
        panelGray1.add(button3);

        button4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/picture/101.png"))); // NOI18N
        button4.setText("Keluar");
        button4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                button4ActionPerformed(evt);
            }
        });
        panelGray1.add(button4);

        internalFrame1.add(panelGray1, java.awt.BorderLayout.PAGE_END);

        scrollPane1.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createEtchedBorder(), "..:: Formulir Pencatatan Psikoterapi ::..", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("sansserif", 0, 11))); // NOI18N
        scrollPane1.setHorizontalScrollBarPolicy(javax.swing.ScrollPaneConstants.HORIZONTAL_SCROLLBAR_ALWAYS);

        label1.setText("Aksis I");
        label1.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N

        txDiag2.setText("-");

        label2.setText("Aksis II");
        label2.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N

        txDiag4.setText("-");
        txDiag4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txDiag4ActionPerformed(evt);
            }
        });

        label3.setText("Aksis II");
        label3.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N

        txDiag3.setText("-");

        txDiag1.setText("-");

        label4.setText("Aksis II");
        label4.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N

        label8.setText("II. PERMASALAH YANG DITEMUKAN (IDENTIFIKASI MASALAH)");
        label8.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N

        txmasalah1.setColumns(20);
        txmasalah1.setRows(5);
        txmasalah1.setText("-");
        jScrollPane1.setViewportView(txmasalah1);

        label9.setText("Prioritas Masalah :");
        label9.setFont(new java.awt.Font("SansSerif", 0, 12)); // NOI18N

        txmasalah2.setColumns(20);
        txmasalah2.setRows(5);
        txmasalah2.setText("-");
        jScrollPane2.setViewportView(txmasalah2);

        label10.setText("I. DIAGNOSIS KERJA");
        label10.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N

        label11.setText("III. KONTRAK TERAPI");
        label11.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N

        terapi1.setBackground(new java.awt.Color(255, 255, 255));
        terapi1.setText("Psikoterapi Individual");

        terapi4.setBackground(new java.awt.Color(255, 255, 255));
        terapi4.setText("Psikoterapi Kelompok");

        terapi2.setBackground(new java.awt.Color(255, 255, 255));
        terapi2.setText("(50 Menit/Minggu)");

        terapi5.setText("-");

        terapi3.setBackground(new java.awt.Color(255, 255, 255));
        terapi3.setText("Psikoterapi Supportif");

        terapi6.setBackground(new java.awt.Color(255, 255, 255));
        terapi6.setText("Psikoterapi Psikoanalisis/Psikodinamis");

        terapi7.setBackground(new java.awt.Color(255, 255, 255));
        terapi7.setText("Psikoterapi Spesifik");

        terapi8.setText("-");

        label12.setText("Psikoterapi Lainnya...");
        label12.setFont(new java.awt.Font("SansSerif", 0, 12)); // NOI18N

        label13.setText("IV. TAHAPAN PSIKOTERAPI");
        label13.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N

        tahapawal1.setBackground(new java.awt.Color(255, 255, 255));
        tahapawal1.setText("Membangun hubungan terapi");

        tahapawal3.setBackground(new java.awt.Color(255, 255, 255));
        tahapawal3.setText("Memperjelas mendefinisikan Masalah");

        tahapawal2.setBackground(new java.awt.Color(255, 255, 255));
        tahapawal2.setText("Negosiasi Kontrak");

        tahapawal4.setBackground(new java.awt.Color(255, 255, 255));
        tahapawal4.setText("Membuat penafsiran & penjajakan");

        label14.setText("1. Tahap awal terapi");
        label14.setFont(new java.awt.Font("SansSerif", 0, 12)); // NOI18N

        tahap6.setBackground(new java.awt.Color(255, 255, 255));
        tahap6.setText("Menjaga hubungan terapi selalu terpelihara");

        tahap5.setBackground(new java.awt.Color(255, 255, 255));
        tahap5.setText("Penjelajahan masalah pasien / klien");

        label15.setText("2. Tahap Pertengahan");
        label15.setFont(new java.awt.Font("SansSerif", 0, 12)); // NOI18N

        label16.setText("CBT");
        label16.setFont(new java.awt.Font("SansSerif", 0, 12)); // NOI18N

        label17.setText("Teknik");
        label17.setFont(new java.awt.Font("SansSerif", 0, 12)); // NOI18N

        tahaptgh1.setBackground(new java.awt.Color(255, 255, 255));
        tahaptgh1.setText("Ventilasi dan Katarsis");

        tahaptgh2.setBackground(new java.awt.Color(255, 255, 255));
        tahaptgh2.setText("Persuasi");

        tahaptgh6.setBackground(new java.awt.Color(255, 255, 255));
        tahaptgh6.setText("Asosiasi bebas");

        tahaptgh5.setBackground(new java.awt.Color(255, 255, 255));
        tahaptgh5.setText("Reassurance/Penjamin Kembali");

        tahaptgh3.setBackground(new java.awt.Color(255, 255, 255));
        tahaptgh3.setText("Interpretasi");

        tahaptgh7.setBackground(new java.awt.Color(255, 255, 255));
        tahaptgh7.setText("Konfrontasi");

        tahaptgh4.setBackground(new java.awt.Color(255, 255, 255));
        tahaptgh4.setText("Intervensi khusus");

        cbt_a.setText("-");

        label18.setText("Activiting Event");
        label18.setFont(new java.awt.Font("SansSerif", 0, 12)); // NOI18N

        label19.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        label19.setText("Belief");
        label19.setFont(new java.awt.Font("SansSerif", 0, 12)); // NOI18N

        cbt_b.setText("-");

        cbt_c.setText("-");

        label20.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        label20.setText("Consequence");
        label20.setFont(new java.awt.Font("SansSerif", 0, 12)); // NOI18N

        label5.setText("No RM");
        label5.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N

        label6.setText("Nama Pasien");
        label6.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N

        label7.setText("No Rawat");
        label7.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N

        label21.setText("Dispute");
        label21.setFont(new java.awt.Font("SansSerif", 0, 12)); // NOI18N

        label22.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        label22.setText("Efek Baru");
        label22.setFont(new java.awt.Font("SansSerif", 0, 12)); // NOI18N

        label23.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        label23.setText("Further Action");
        label23.setFont(new java.awt.Font("SansSerif", 0, 12)); // NOI18N

        cbt_f.setText("-");

        cbt_e.setText("-");
        cbt_e.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbt_eActionPerformed(evt);
            }
        });

        cbt_d.setText("-");

        label24.setText("3. Tahap akhir terapi");
        label24.setFont(new java.awt.Font("SansSerif", 0, 12)); // NOI18N

        jRadioButton15.setBackground(new java.awt.Color(255, 255, 255));
        jRadioButton15.setText("Memutuskan perubahan sikap & perilaku yang memadai");

        jRadioButton24.setBackground(new java.awt.Color(255, 255, 255));
        jRadioButton24.setText("Mengakhiri hubungan terapi");

        jRadioButton25.setBackground(new java.awt.Color(255, 255, 255));
        jRadioButton25.setText("Melaksanakan pembahasan perilaku");

        label25.setText("IV. TAHAPAN PSIKOTERAPI");
        label25.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N

        textArea3.setColumns(20);
        textArea3.setRows(5);
        textArea3.setText("-");
        jScrollPane3.setViewportView(textArea3);

        label26.setText("Lainnya...");
        label26.setFont(new java.awt.Font("SansSerif", 0, 12)); // NOI18N

        javax.swing.GroupLayout panelGray4Layout = new javax.swing.GroupLayout(panelGray4);
        panelGray4.setLayout(panelGray4Layout);
        panelGray4Layout.setHorizontalGroup(
            panelGray4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelGray4Layout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addGroup(panelGray4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panelGray4Layout.createSequentialGroup()
                        .addGap(19, 19, 19)
                        .addGroup(panelGray4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(panelGray4Layout.createSequentialGroup()
                                .addGroup(panelGray4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(label14, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(panelGray4Layout.createSequentialGroup()
                                        .addGroup(panelGray4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(tahapawal1)
                                            .addComponent(tahapawal2))
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addGroup(panelGray4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(tahapawal4)
                                            .addComponent(tahapawal3))))
                                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addGroup(panelGray4Layout.createSequentialGroup()
                                .addGroup(panelGray4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(label15, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(panelGray4Layout.createSequentialGroup()
                                        .addComponent(tahap5)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(tahap6))
                                    .addGroup(panelGray4Layout.createSequentialGroup()
                                        .addGap(22, 22, 22)
                                        .addGroup(panelGray4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(label17, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addGroup(panelGray4Layout.createSequentialGroup()
                                                .addGap(6, 6, 6)
                                                .addGroup(panelGray4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                    .addComponent(tahaptgh1)
                                                    .addComponent(tahaptgh2)
                                                    .addComponent(tahaptgh3)
                                                    .addComponent(tahaptgh4))
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                                .addGroup(panelGray4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                    .addComponent(tahaptgh7)
                                                    .addComponent(tahaptgh5)
                                                    .addComponent(tahaptgh6)))))
                                    .addComponent(label24, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(panelGray4Layout.createSequentialGroup()
                                        .addGap(17, 17, 17)
                                        .addGroup(panelGray4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jRadioButton24)
                                            .addComponent(jRadioButton25)
                                            .addGroup(panelGray4Layout.createSequentialGroup()
                                                .addComponent(jRadioButton15)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 185, Short.MAX_VALUE)
                                                .addGroup(panelGray4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                                    .addGroup(panelGray4Layout.createSequentialGroup()
                                                        .addGroup(panelGray4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                            .addComponent(label21, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                            .addComponent(label23, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                            .addComponent(label22, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                                        .addGap(18, 18, 18)
                                                        .addGroup(panelGray4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                            .addGroup(panelGray4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                                .addComponent(cbt_e, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 421, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                                .addComponent(cbt_f, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 421, javax.swing.GroupLayout.PREFERRED_SIZE))
                                                            .addComponent(cbt_d, javax.swing.GroupLayout.PREFERRED_SIZE, 421, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                                    .addGroup(panelGray4Layout.createSequentialGroup()
                                                        .addGroup(panelGray4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                            .addComponent(label18, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                            .addComponent(label20, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                            .addComponent(label19, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                            .addComponent(label16, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                                        .addGroup(panelGray4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                            .addGroup(panelGray4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                                .addComponent(cbt_b, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 421, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                                .addComponent(cbt_c, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 421, javax.swing.GroupLayout.PREFERRED_SIZE))
                                                            .addComponent(cbt_a, javax.swing.GroupLayout.PREFERRED_SIZE, 421, javax.swing.GroupLayout.PREFERRED_SIZE))))))))
                                .addGap(68, 68, 68))))
                    .addGroup(panelGray4Layout.createSequentialGroup()
                        .addGroup(panelGray4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(panelGray4Layout.createSequentialGroup()
                                .addGap(6, 6, 6)
                                .addComponent(jScrollPane3))
                            .addGroup(panelGray4Layout.createSequentialGroup()
                                .addGroup(panelGray4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(label13, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(label11, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(panelGray4Layout.createSequentialGroup()
                                        .addGap(21, 21, 21)
                                        .addGroup(panelGray4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addGroup(panelGray4Layout.createSequentialGroup()
                                                .addComponent(terapi3)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                                .addComponent(terapi6)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                                .addComponent(terapi7))
                                            .addGroup(panelGray4Layout.createSequentialGroup()
                                                .addComponent(label12, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addComponent(terapi8, javax.swing.GroupLayout.PREFERRED_SIZE, 258, javax.swing.GroupLayout.PREFERRED_SIZE))
                                            .addGroup(panelGray4Layout.createSequentialGroup()
                                                .addGroup(panelGray4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                    .addComponent(terapi1)
                                                    .addComponent(terapi2))
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                                .addGroup(panelGray4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                    .addGroup(panelGray4Layout.createSequentialGroup()
                                                        .addComponent(label26, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                        .addGap(2, 2, 2)
                                                        .addComponent(terapi5, javax.swing.GroupLayout.PREFERRED_SIZE, 258, javax.swing.GroupLayout.PREFERRED_SIZE))
                                                    .addComponent(terapi4)))))
                                    .addGroup(panelGray4Layout.createSequentialGroup()
                                        .addGap(14, 14, 14)
                                        .addGroup(panelGray4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                            .addComponent(label4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addGroup(panelGray4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                                .addComponent(txDiag3, javax.swing.GroupLayout.PREFERRED_SIZE, 139, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addGroup(panelGray4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                                    .addGroup(panelGray4Layout.createSequentialGroup()
                                                        .addComponent(label1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                                        .addComponent(txDiag1, javax.swing.GroupLayout.PREFERRED_SIZE, 138, javax.swing.GroupLayout.PREFERRED_SIZE))
                                                    .addGroup(panelGray4Layout.createSequentialGroup()
                                                        .addComponent(label3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                        .addComponent(txDiag2, javax.swing.GroupLayout.PREFERRED_SIZE, 139, javax.swing.GroupLayout.PREFERRED_SIZE))))
                                            .addGroup(panelGray4Layout.createSequentialGroup()
                                                .addComponent(label2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addComponent(txDiag4, javax.swing.GroupLayout.PREFERRED_SIZE, 139, javax.swing.GroupLayout.PREFERRED_SIZE))))
                                    .addGroup(panelGray4Layout.createSequentialGroup()
                                        .addComponent(label7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(txNoRwt, javax.swing.GroupLayout.PREFERRED_SIZE, 143, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(18, 18, 18)
                                        .addComponent(label5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(txNoRM, javax.swing.GroupLayout.PREFERRED_SIZE, 143, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(18, 18, 18)
                                        .addComponent(label6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(txnmPas, javax.swing.GroupLayout.PREFERRED_SIZE, 243, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addComponent(label10, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(panelGray4Layout.createSequentialGroup()
                                        .addGroup(panelGray4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(label8, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addGroup(panelGray4Layout.createSequentialGroup()
                                                .addGap(20, 20, 20)
                                                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 431, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                        .addGap(18, 18, 18)
                                        .addGroup(panelGray4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(label9, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 447, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                    .addComponent(label25, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(0, 0, Short.MAX_VALUE)))
                        .addContainerGap())))
        );
        panelGray4Layout.setVerticalGroup(
            panelGray4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelGray4Layout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addGroup(panelGray4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(label7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txNoRwt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(label5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txNoRM, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txnmPas, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(label6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(30, 30, 30)
                .addComponent(label10, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(7, 7, 7)
                .addGroup(panelGray4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(label1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txDiag1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(panelGray4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(label3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txDiag2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(panelGray4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(label4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txDiag3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(panelGray4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(label2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txDiag4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(panelGray4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(panelGray4Layout.createSequentialGroup()
                        .addComponent(label8, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 102, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(panelGray4Layout.createSequentialGroup()
                        .addComponent(label9, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 102, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(18, 18, 18)
                .addComponent(label11, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(panelGray4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(terapi1)
                    .addComponent(terapi4))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(panelGray4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(terapi2)
                    .addComponent(terapi5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(label26, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(panelGray4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(terapi3)
                    .addComponent(terapi6)
                    .addComponent(terapi7))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(panelGray4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(terapi8, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(label12, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(label13, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(label14, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(panelGray4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(tahapawal1)
                    .addComponent(tahapawal3))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(panelGray4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(tahapawal2)
                    .addComponent(tahapawal4))
                .addGap(18, 18, 18)
                .addComponent(label15, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(1, 1, 1)
                .addGroup(panelGray4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panelGray4Layout.createSequentialGroup()
                        .addGroup(panelGray4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(tahap5)
                            .addComponent(tahap6))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(label17, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(panelGray4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(tahaptgh1)
                            .addComponent(tahaptgh5))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(panelGray4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(tahaptgh2)
                            .addComponent(tahaptgh6))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(panelGray4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(tahaptgh7)
                            .addComponent(tahaptgh3))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(tahaptgh4)
                        .addGap(18, 18, 18)
                        .addComponent(label24, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jRadioButton15))
                    .addGroup(panelGray4Layout.createSequentialGroup()
                        .addComponent(label16, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(panelGray4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(cbt_a, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(label18, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(panelGray4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(cbt_b, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(label19, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(panelGray4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(cbt_c, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(label20, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(panelGray4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(cbt_d, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(label21, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(panelGray4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(cbt_e, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(label22, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(panelGray4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(cbt_f, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(label23, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jRadioButton24)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jRadioButton25)
                .addGap(18, 18, 18)
                .addComponent(label25, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        scrollPane1.setViewportView(panelGray4);

        internalFrame1.add(scrollPane1, java.awt.BorderLayout.CENTER);

        getContentPane().add(internalFrame1, java.awt.BorderLayout.CENTER);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    public void setNo(String noRw, String nmPasien, String noRM, String Diag){
        txNoRwt.setText(noRw);
        txnmPas.setText(nmPasien);
        txNoRM.setText(noRM);
        txDiag1.setText(Diag);
    }
    
    private void txDiag4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txDiag4ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txDiag4ActionPerformed

    private void button4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_button4ActionPerformed
        dispose();
    }//GEN-LAST:event_button4ActionPerformed

    private void cbt_eActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbt_eActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cbt_eActionPerformed

    private void button1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_button1ActionPerformed
     try {
        ps = koneksi.prepareStatement("insert into pencatatan_psikoterapi value (?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?)");
        ps.setString(1, txDiag1.getText());
        ps.executeUpdate();
         JOptionPane.showMessageDialog(null, "Berhasil");
     }catch(Exception e){
         System.out.println("Error : "+e.getMessage());
     }
    }//GEN-LAST:event_button1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(DlgCatatPsikoterapi.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(DlgCatatPsikoterapi.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(DlgCatatPsikoterapi.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(DlgCatatPsikoterapi.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                DlgCatatPsikoterapi dialog = new DlgCatatPsikoterapi(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup bg1;
    private widget.Button button1;
    private widget.Button button2;
    private widget.Button button3;
    private widget.Button button4;
    private widget.TextBox cbt_a;
    private widget.TextBox cbt_b;
    private widget.TextBox cbt_c;
    private widget.TextBox cbt_d;
    private widget.TextBox cbt_e;
    private widget.TextBox cbt_f;
    private widget.InternalFrame internalFrame1;
    private javax.swing.JRadioButton jRadioButton15;
    private javax.swing.JRadioButton jRadioButton24;
    private javax.swing.JRadioButton jRadioButton25;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private widget.Label label1;
    private widget.Label label10;
    private widget.Label label11;
    private widget.Label label12;
    private widget.Label label13;
    private widget.Label label14;
    private widget.Label label15;
    private widget.Label label16;
    private widget.Label label17;
    private widget.Label label18;
    private widget.Label label19;
    private widget.Label label2;
    private widget.Label label20;
    private widget.Label label21;
    private widget.Label label22;
    private widget.Label label23;
    private widget.Label label24;
    private widget.Label label25;
    private widget.Label label26;
    private widget.Label label3;
    private widget.Label label4;
    private widget.Label label5;
    private widget.Label label6;
    private widget.Label label7;
    private widget.Label label8;
    private widget.Label label9;
    private widget.PanelGray panelGray1;
    private widget.PanelGray panelGray4;
    private widget.ScrollPane scrollPane1;
    private javax.swing.JRadioButton tahap5;
    private javax.swing.JRadioButton tahap6;
    private javax.swing.JRadioButton tahapawal1;
    private javax.swing.JRadioButton tahapawal2;
    private javax.swing.JRadioButton tahapawal3;
    private javax.swing.JRadioButton tahapawal4;
    private javax.swing.JRadioButton tahaptgh1;
    private javax.swing.JRadioButton tahaptgh2;
    private javax.swing.JRadioButton tahaptgh3;
    private javax.swing.JRadioButton tahaptgh4;
    private javax.swing.JRadioButton tahaptgh5;
    private javax.swing.JRadioButton tahaptgh6;
    private javax.swing.JRadioButton tahaptgh7;
    private javax.swing.JRadioButton terapi1;
    private javax.swing.JRadioButton terapi2;
    private javax.swing.JRadioButton terapi3;
    private javax.swing.JRadioButton terapi4;
    private widget.TextBox terapi5;
    private javax.swing.JRadioButton terapi6;
    private javax.swing.JRadioButton terapi7;
    private widget.TextBox terapi8;
    private widget.TextArea textArea3;
    private widget.TextBox txDiag1;
    private widget.TextBox txDiag2;
    private widget.TextBox txDiag3;
    private widget.TextBox txDiag4;
    private widget.TextBox txNoRM;
    private widget.TextBox txNoRwt;
    private widget.TextArea txmasalah1;
    private widget.TextArea txmasalah2;
    private widget.TextBox txnmPas;
    // End of variables declaration//GEN-END:variables
}
