/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JDialog.java to edit this template
 */
package rekammedis;

import fungsi.koneksiDB;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.text.SimpleDateFormat;
import java.util.Calendar;
import java.util.HashMap;
import java.util.Map;
import javax.swing.JOptionPane;
import fungsi.sekuel;
import fungsi.validasi;
import java.sql.ResultSet;

/**
 *
 * @author firka
 */
public class DlgPsikoterapiSupportif extends javax.swing.JDialog {
private Connection koneksi = koneksiDB.condb();
private PreparedStatement ps;
private ResultSet rs;
private validasi Valid = new validasi();
private sekuel sequel = new sekuel();
private String NULL;
private String dateStamp = new SimpleDateFormat("yyyy-MM-dd").format(Calendar.getInstance().getTime());
    /**
     * Creates new form DlgPsikoterapiSupportif
     */
    public DlgPsikoterapiSupportif(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        internalFrame1 = new widget.InternalFrame();
        scrollPane1 = new widget.ScrollPane();
        panelGray1 = new widget.PanelGray();
        label1 = new widget.Label();
        soal11 = new widget.RadioButton();
        soal13 = new widget.RadioButton();
        soal12 = new widget.RadioButton();
        label2 = new widget.Label();
        soal21 = new widget.RadioButton();
        soal22 = new widget.RadioButton();
        soal23 = new widget.RadioButton();
        label3 = new widget.Label();
        soal31 = new widget.RadioButton();
        soal32 = new widget.RadioButton();
        soal33 = new widget.RadioButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        soal24 = new widget.TextArea();
        jScrollPane2 = new javax.swing.JScrollPane();
        soal14 = new widget.TextArea();
        jScrollPane3 = new javax.swing.JScrollPane();
        soal34 = new widget.TextArea();
        label4 = new widget.Label();
        soal41 = new widget.RadioButton();
        soal42 = new widget.RadioButton();
        soal43 = new widget.RadioButton();
        jScrollPane4 = new javax.swing.JScrollPane();
        soal44 = new widget.TextArea();
        label5 = new widget.Label();
        jScrollPane5 = new javax.swing.JScrollPane();
        soal5 = new widget.TextArea();
        label6 = new widget.Label();
        jScrollPane6 = new javax.swing.JScrollPane();
        soal6 = new widget.TextArea();
        panelGray2 = new widget.PanelGray();
        btSimpan = new widget.Button();
        button2 = new widget.Button();
        btEdit = new widget.Button();
        button4 = new widget.Button();
        panelGray3 = new widget.PanelGray();
        label7 = new widget.Label();
        NoRwt = new widget.TextBox();
        label8 = new widget.Label();
        nmPasien = new widget.TextBox();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setUndecorated(true);

        internalFrame1.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createEtchedBorder(), "..:: Formulir Psikoterapi Supportif ::..", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("sansserif", 0, 11))); // NOI18N
        internalFrame1.setLayout(new java.awt.BorderLayout());

        label1.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        label1.setText("I. Tujuan Psikoterapi Supportif");
        label1.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N

        soal11.setText("Mendukung fungsi ego/memperkuat mekanisme defense yang ada");

        soal13.setText("Perbaikan keadaan, keseimbangan tang lebih adaptif");
        soal13.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                soal13ActionPerformed(evt);
            }
        });

        soal12.setText("Memperluas pengendalian yang dimiliki dengan yang baru dan lebih baik");

        label2.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        label2.setText("II. Tahapan / Waktu (sebutkan lama waktu berlangsung psikoterapi)");
        label2.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N

        soal21.setText("Tahap Awal (membangun hubungan terapi, definisi masalah, penafsiran dan penjajakan, negosiasi kontrak)");

        soal22.setText("Tahap Pertengahan (penjelajahan masalah, bantuan berdasar penilaian eksplorasi masalah, menjaga hubungan terapentik)");

        soal23.setText("Tahap Akhir (memutuskan perubahan sikap/perilaku yang memadai melakukan perubahan perilaku, mengakhiri hubungan terapi)");
        soal23.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                soal23ActionPerformed(evt);
            }
        });

        label3.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        label3.setText("III. Data Kllinis Pasien");
        label3.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N

        soal31.setText("Laporan pasien mengenai aktivitas harian");

        soal32.setText("Keterlibatan antara pribadi terhadap terapis dan orang lain");

        soal33.setText("Kemampuan membuat keputusan");
        soal33.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                soal33ActionPerformed(evt);
            }
        });

        soal24.setColumns(20);
        soal24.setRows(5);
        jScrollPane1.setViewportView(soal24);

        soal14.setColumns(20);
        soal14.setRows(5);
        soal14.setDisabledTextColor(new java.awt.Color(255, 255, 255));
        jScrollPane2.setViewportView(soal14);

        soal34.setColumns(20);
        soal34.setRows(5);
        jScrollPane3.setViewportView(soal34);

        label4.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        label4.setText("IV. Teknik yang digunakan");
        label4.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N

        soal41.setText("Ventilasi / Katarsis (kesempatan untuk mengutamakan problem emosi)");

        soal42.setText("Persuasi (menjelaskan timbulnya gejala)");

        soal43.setText("Sugesti (penjaminan kembali, mengingatkan potensi dan kemampuan pasien)");
        soal43.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                soal43ActionPerformed(evt);
            }
        });

        soal44.setColumns(20);
        soal44.setRows(5);
        jScrollPane4.setViewportView(soal44);

        label5.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        label5.setText("V. Hambatan / Resistensi (pada pasien maupun terapis)");
        label5.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N

        soal5.setColumns(20);
        soal5.setRows(5);
        jScrollPane5.setViewportView(soal5);

        label6.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        label6.setText("VI. Tindak Lanjut (rencana untuk kunjungan berikutnya)");
        label6.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N

        soal6.setColumns(20);
        soal6.setRows(5);
        jScrollPane6.setViewportView(soal6);

        javax.swing.GroupLayout panelGray1Layout = new javax.swing.GroupLayout(panelGray1);
        panelGray1.setLayout(panelGray1Layout);
        panelGray1Layout.setHorizontalGroup(
            panelGray1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelGray1Layout.createSequentialGroup()
                .addGroup(panelGray1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panelGray1Layout.createSequentialGroup()
                        .addGap(23, 23, 23)
                        .addGroup(panelGray1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(label1, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(panelGray1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(label2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGroup(panelGray1Layout.createSequentialGroup()
                                    .addGap(6, 6, 6)
                                    .addGroup(panelGray1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                        .addGroup(panelGray1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addGroup(panelGray1Layout.createSequentialGroup()
                                                .addGap(12, 12, 12)
                                                .addComponent(jScrollPane6, javax.swing.GroupLayout.PREFERRED_SIZE, 635, javax.swing.GroupLayout.PREFERRED_SIZE))
                                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelGray1Layout.createSequentialGroup()
                                                .addComponent(label6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addGap(332, 332, 332)))
                                        .addGroup(panelGray1Layout.createSequentialGroup()
                                            .addGap(6, 6, 6)
                                            .addGroup(panelGray1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                                .addGroup(panelGray1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                    .addComponent(soal42, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                    .addComponent(soal41, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                    .addComponent(soal43, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                    .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 635, javax.swing.GroupLayout.PREFERRED_SIZE))
                                                .addGroup(panelGray1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                    .addComponent(soal32, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                    .addComponent(soal31, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                    .addComponent(soal33, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                    .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 635, javax.swing.GroupLayout.PREFERRED_SIZE))
                                                .addComponent(jScrollPane5, javax.swing.GroupLayout.PREFERRED_SIZE, 635, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                                .addComponent(label4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(label3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelGray1Layout.createSequentialGroup()
                                    .addComponent(label5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGap(332, 332, 332))
                                .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 643, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(panelGray1Layout.createSequentialGroup()
                        .addGap(36, 36, 36)
                        .addGroup(panelGray1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(panelGray1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(soal22, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(soal21, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(soal23, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addGroup(panelGray1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(soal12, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(soal11, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(soal13, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 635, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addContainerGap(713, Short.MAX_VALUE))
        );
        panelGray1Layout.setVerticalGroup(
            panelGray1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelGray1Layout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addComponent(label1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(soal11, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(soal12, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(soal13, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(label2, javax.swing.GroupLayout.PREFERRED_SIZE, 14, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(soal21, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(soal22, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(soal23, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(label3, javax.swing.GroupLayout.PREFERRED_SIZE, 14, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(soal31, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(soal32, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(soal33, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(label4, javax.swing.GroupLayout.PREFERRED_SIZE, 14, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(soal41, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(soal42, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(soal43, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(label5, javax.swing.GroupLayout.PREFERRED_SIZE, 14, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(label6, javax.swing.GroupLayout.PREFERRED_SIZE, 14, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(26, Short.MAX_VALUE))
        );

        scrollPane1.setViewportView(panelGray1);

        internalFrame1.add(scrollPane1, java.awt.BorderLayout.CENTER);

        btSimpan.setIcon(new javax.swing.ImageIcon(getClass().getResource("/picture/095.png"))); // NOI18N
        btSimpan.setText("Simpan");
        btSimpan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btSimpanActionPerformed(evt);
            }
        });
        panelGray2.add(btSimpan);

        button2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/picture/PrinterSettings.png"))); // NOI18N
        button2.setText("Cetak");
        button2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                button2ActionPerformed(evt);
            }
        });
        panelGray2.add(button2);

        btEdit.setIcon(new javax.swing.ImageIcon(getClass().getResource("/picture/EDIT2.png"))); // NOI18N
        btEdit.setText("Ganti");
        btEdit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btEditActionPerformed(evt);
            }
        });
        panelGray2.add(btEdit);

        button4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/picture/101.png"))); // NOI18N
        button4.setText("Keluar");
        button4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                button4ActionPerformed(evt);
            }
        });
        panelGray2.add(button4);

        internalFrame1.add(panelGray2, java.awt.BorderLayout.PAGE_END);

        label7.setText("No Rawat");

        label8.setText("Nama Pasien");

        javax.swing.GroupLayout panelGray3Layout = new javax.swing.GroupLayout(panelGray3);
        panelGray3.setLayout(panelGray3Layout);
        panelGray3Layout.setHorizontalGroup(
            panelGray3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelGray3Layout.createSequentialGroup()
                .addGap(17, 17, 17)
                .addComponent(label7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(NoRwt, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(31, 31, 31)
                .addComponent(label8, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(nmPasien, javax.swing.GroupLayout.PREFERRED_SIZE, 212, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(252, Short.MAX_VALUE))
        );
        panelGray3Layout.setVerticalGroup(
            panelGray3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelGray3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panelGray3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(label7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(NoRwt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(panelGray3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(label8, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(nmPasien, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(16, Short.MAX_VALUE))
        );

        internalFrame1.add(panelGray3, java.awt.BorderLayout.PAGE_START);

        getContentPane().add(internalFrame1, java.awt.BorderLayout.CENTER);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void soal13ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_soal13ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_soal13ActionPerformed

    private void soal23ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_soal23ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_soal23ActionPerformed

    private void soal33ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_soal33ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_soal33ActionPerformed

    private void soal43ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_soal43ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_soal43ActionPerformed

    public void setNo(String norwt, String nmPas){
        NoRwt.setText(norwt);
        nmPasien.setText(nmPas);
    }
    
    private void simpan(){
        try {
            ps = koneksi.prepareStatement("insert into pencatatan_psiko_supportif values(?,?,?,?,?,?,?,?,?,?,?,?,?)");
            ps.setString(1, NoRwt.getText());
            ps.setString(2, dateStamp);
            ps.setString(3, soal11.getText());
            ps.setString(4, soal14.getText());
            ps.setString(5, soal21.getText());
            ps.setString(6, soal24.getText());
            ps.setString(7, soal31.getText());
            ps.setString(8, soal34.getText());
            ps.setString(9, soal41.getText());
            ps.setString(10, soal44.getText());
            ps.setString(11, soal5.getText());
            ps.setString(12, soal6.getText());
            ps.setString(13, NULL);
         JOptionPane.showMessageDialog(null, "Tersimpan");
       }catch(Exception e){
           System.out.println("Error : "+e.getMessage());
       }
    }
    
    private void btSimpanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btSimpanActionPerformed
        cek();
       
    }//GEN-LAST:event_btSimpanActionPerformed

    private void button2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_button2ActionPerformed
        Map<String, Object> param = new HashMap<>();
        param.put("logo",sequel.cariGambar("select setting.logo from setting"));
        Valid.MyReportqry("penilaian_supportif.jasper", "report", "::[ Laporan Psikoterapi Supportif ]::", "SELECT reg_periksa.no_rkm_medis, pasien.nm_pasien, pencatatan_psiko_supportif.*, dokter.nm_dokter FROM reg_periksa\n" +
    "  INNER JOIN pasien ON reg_periksa.no_rkm_medis = pasien.no_rkm_medis \n" +
    "  INNER JOIN pencatatan_psiko_supportif ON pencatatan_psiko_supportif.no_rawat = reg_periksa.no_rawat\n" +
    "  INNER JOIN dokter ON reg_periksa.kd_dokter = dokter.kd_dokter where pencatatan_psiko_supportif.no_rawat='"+NoRwt.getText()+"'",param);
        
    }//GEN-LAST:event_button2ActionPerformed

    private void button4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_button4ActionPerformed
        dispose();
    }//GEN-LAST:event_button4ActionPerformed

    private void cek(){
        try {
        ps = koneksi.prepareStatement("select count(*) from pencatatan_psiko_supportif where no_rawat like ? and tanggal like ?");
        ps.setString(1, NoRwt.getText());
        ps.setString(2, dateStamp);
        rs = ps.executeQuery();
            if (rs.getRow()==0){
                 simpan();
            }else{
                JOptionPane.showMessageDialog(null, "Anda sdh input hari ini, silahkan cek riwayat");
            }
        }catch(Exception e){
            System.out.println("Error : "+e.getMessage());
        }
        
    }
    
    private void btEditActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btEditActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btEditActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(DlgPsikoterapiSupportif.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(DlgPsikoterapiSupportif.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(DlgPsikoterapiSupportif.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(DlgPsikoterapiSupportif.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                DlgPsikoterapiSupportif dialog = new DlgPsikoterapiSupportif(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private widget.TextBox NoRwt;
    private widget.Button btEdit;
    private widget.Button btSimpan;
    private widget.Button button2;
    private widget.Button button4;
    private widget.InternalFrame internalFrame1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JScrollPane jScrollPane5;
    private javax.swing.JScrollPane jScrollPane6;
    private widget.Label label1;
    private widget.Label label2;
    private widget.Label label3;
    private widget.Label label4;
    private widget.Label label5;
    private widget.Label label6;
    private widget.Label label7;
    private widget.Label label8;
    private widget.TextBox nmPasien;
    private widget.PanelGray panelGray1;
    private widget.PanelGray panelGray2;
    private widget.PanelGray panelGray3;
    private widget.ScrollPane scrollPane1;
    private widget.RadioButton soal11;
    private widget.RadioButton soal12;
    private widget.RadioButton soal13;
    private widget.TextArea soal14;
    private widget.RadioButton soal21;
    private widget.RadioButton soal22;
    private widget.RadioButton soal23;
    private widget.TextArea soal24;
    private widget.RadioButton soal31;
    private widget.RadioButton soal32;
    private widget.RadioButton soal33;
    private widget.TextArea soal34;
    private widget.RadioButton soal41;
    private widget.RadioButton soal42;
    private widget.RadioButton soal43;
    private widget.TextArea soal44;
    private widget.TextArea soal5;
    private widget.TextArea soal6;
    // End of variables declaration//GEN-END:variables
}
