/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JDialog.java to edit this template
 */
package bridging;

import fungsi.koneksiDB;
import fungsi.validasi;
import java.awt.Dimension;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import javax.swing.JTable;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableColumn;

/**
 *
 * @author firka
 */
public class RiwayatTaskID extends javax.swing.JDialog {
 private final DefaultTableModel tabMode;
    private validasi Valid=new validasi();
    private Connection koneksi=koneksiDB.condb();
    private PreparedStatement ps,psID;
    private ResultSet rs,rsID;   
    private int i;
    /**
     * Creates new form RiwayatTaskID
     */
    public RiwayatTaskID(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        
        tabMode=new DefaultTableModel(null,new Object[]{
                "No.Rawat","No.RM","Nama Pasien","Tgl Registrasi","No.KTP","Telepon","Poli","Dokter",
                "Waktu","Waktu RS","Task ID","Jns Layanan"
            }){
             @Override public boolean isCellEditable(int rowIndex, int colIndex){return false;}
        };
        tbRiwayat.setModel(tabMode);

        tbRiwayat.setPreferredScrollableViewportSize(new Dimension(500,500));
        tbRiwayat.setAutoResizeMode(JTable.AUTO_RESIZE_OFF);

        for (i = 0; i < 12; i++) {
            TableColumn column = tbRiwayat.getColumnModel().getColumn(i);
            if(i==0){
                column.setPreferredWidth(110);
            }else if(i==1){
                column.setPreferredWidth(85);
            }else if(i==2){
                column.setPreferredWidth(180);
            }else if(i==3){
                column.setPreferredWidth(80);
            }else if(i==4){
                column.setPreferredWidth(90);
            }else if(i==5){
                column.setPreferredWidth(90);
            }else if(i==6){
                column.setPreferredWidth(150);
            }else if(i==7){
                column.setPreferredWidth(150);
            }else if(i==8){
                column.setPreferredWidth(150);
            }else if(i==9){
                column.setPreferredWidth(150);
            }else if(i==10){
                column.setPreferredWidth(120);
            }else if(i==11){
                column.setPreferredWidth(120);
            }
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        internalFrame1 = new widget.InternalFrame();
        panelBiasa1 = new widget.PanelBiasa();
        label2 = new widget.Label();
        tanggal1 = new widget.Tanggal();
        label1 = new widget.Label();
        tanggal2 = new widget.Tanggal();
        button2 = new widget.Button();
        label3 = new widget.Label();
        label4 = new widget.Label();
        panelisi1 = new widget.panelisi();
        button1 = new widget.Button();
        jScrollPane1 = new javax.swing.JScrollPane();
        tbRiwayat = new widget.Table();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setUndecorated(true);

        internalFrame1.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createEtchedBorder(), "..:: Riwayat TaskID ::..", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("sansserif", 0, 11))); // NOI18N
        internalFrame1.setLayout(new java.awt.BorderLayout());

        label2.setText("Tanggal : ");
        label2.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        panelBiasa1.add(label2);

        tanggal1.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "11/12/2023" }));
        tanggal1.setDisplayFormat("dd/MM/yyyy");
        panelBiasa1.add(tanggal1);

        label1.setText("s/d");
        label1.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        panelBiasa1.add(label1);

        tanggal2.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "11/12/2023" }));
        tanggal2.setDisplayFormat("dd/MM/yyyy");
        panelBiasa1.add(tanggal2);

        button2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/picture/accept.png"))); // NOI18N
        button2.setPreferredSize(new java.awt.Dimension(45, 32));
        button2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                button2ActionPerformed(evt);
            }
        });
        panelBiasa1.add(button2);

        label3.setText("Record :");
        label3.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        panelBiasa1.add(label3);

        label4.setText("0");
        label4.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        panelBiasa1.add(label4);

        panelisi1.setPreferredSize(new java.awt.Dimension(300, 24));

        javax.swing.GroupLayout panelisi1Layout = new javax.swing.GroupLayout(panelisi1);
        panelisi1.setLayout(panelisi1Layout);
        panelisi1Layout.setHorizontalGroup(
            panelisi1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 298, Short.MAX_VALUE)
        );
        panelisi1Layout.setVerticalGroup(
            panelisi1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 22, Short.MAX_VALUE)
        );

        panelBiasa1.add(panelisi1);

        button1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/picture/101.png"))); // NOI18N
        button1.setText("Keluar");
        button1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                button1ActionPerformed(evt);
            }
        });
        panelBiasa1.add(button1);

        internalFrame1.add(panelBiasa1, java.awt.BorderLayout.PAGE_END);

        tbRiwayat.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {

            }
        ));
        jScrollPane1.setViewportView(tbRiwayat);

        internalFrame1.add(jScrollPane1, java.awt.BorderLayout.CENTER);

        getContentPane().add(internalFrame1, java.awt.BorderLayout.CENTER);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void button1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_button1ActionPerformed
        dispose();
    }//GEN-LAST:event_button1ActionPerformed

    private void button2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_button2ActionPerformed
        try{
            ps=koneksi.prepareStatement("SELECT reg_periksa.no_rawat, pasien.no_rkm_medis, pasien.nm_pasien, task_id_bpjs.tgl_registrasi, pasien.no_ktp, pasien.no_tlp, poliklinik.nm_poli,\n" +
            "dokter.nm_dokter, reg_periksa.status_lanjut,task_id_bpjs.waktu, task_id_bpjs.waktuRS, GROUP_CONCAT(task_id_bpjs.taskID ORDER BY task_id_bpjs.taskID ASC) AS TaskID\n" +
            "FROM reg_periksa INNER JOIN pasien ON reg_periksa.no_rkm_medis = pasien.no_rkm_medis\n" +
            "INNER JOIN task_id_bpjs ON task_id_bpjs.no_rawat = reg_periksa.no_rawat\n" +
            "INNER JOIN poliklinik ON reg_periksa.kd_poli = poliklinik.kd_poli\n" +
            "INNER JOIN dokter ON reg_periksa.kd_dokter = dokter.kd_dokter\n" +
            "WHERE task_id_bpjs.tgl_registrasi between ? and ? GROUP BY task_id_bpjs.no_rawat ORDER BY task_id_bpjs.tgl_registrasi");
            ps.setString(1, Valid.SetTgl(tanggal1.getSelectedItem()+""));
            ps.setString(2, Valid.SetTgl(tanggal2.getSelectedItem()+""));
            rs=ps.executeQuery();
            tabMode.setRowCount(0);
            while(rs.next()){
                tabMode.addRow(new Object []{
                rs.getString("no_rawat"),rs.getString("no_rkm_medis"),rs.getString("nm_pasien"),rs.getString("tgl_registrasi"),
                rs.getString("no_ktp"), rs.getString("no_tlp"),rs.getString("nm_poli"),rs.getString("nm_dokter"), rs.getString("waktu"),
                rs.getString("waktuRS"),rs.getString("TaskID"),rs.getString("status_lanjut")
                });
            }
            label4.setText(Integer.toString(tbRiwayat.getRowCount()));
        }catch(Exception e){
            System.out.println("Error Tampil : "+e.getMessage());
        }
    }//GEN-LAST:event_button2ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(RiwayatTaskID.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(RiwayatTaskID.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(RiwayatTaskID.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(RiwayatTaskID.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                RiwayatTaskID dialog = new RiwayatTaskID(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private widget.Button button1;
    private widget.Button button2;
    private widget.InternalFrame internalFrame1;
    private javax.swing.JScrollPane jScrollPane1;
    private widget.Label label1;
    private widget.Label label2;
    private widget.Label label3;
    private widget.Label label4;
    private widget.PanelBiasa panelBiasa1;
    private widget.panelisi panelisi1;
    private widget.Tanggal tanggal1;
    private widget.Tanggal tanggal2;
    private widget.Table tbRiwayat;
    // End of variables declaration//GEN-END:variables
}
