/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JDialog.java to edit this template
 */
package simrskhanza;

import fungsi.koneksiDB;
import fungsi.sekuel;
import fungsi.validasi;
import java.awt.Dimension;
import java.sql.Connection;
import java.awt.event.KeyEvent;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.text.SimpleDateFormat;
import java.util.Calendar;
import javax.swing.JTable;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableColumn;

/**
 *
 * @author firka
 */
public class DlgDaftarPaket extends javax.swing.JDialog {
    private ResultSet rs;
    public int tot,totNoDes, jml;
    private validasi Valid = new validasi();
    private sekuel sequel = new sekuel();
    private Connection koneksi = koneksiDB.condb();
    private PreparedStatement ps;
    private String NULL;
    private int i;
    public int ii;
    private DefaultTableModel tabMode,tabMode2,tabMode3,tabMode4,tabMode5;
    private String dateStamp = new SimpleDateFormat("yyyy-MM-dd").format(Calendar.getInstance().getTime());
    private String timeStamp = new SimpleDateFormat("HH:mm:ss").format(Calendar.getInstance().getTime());
    /**
     * Creates new form DlgDaftarPaket
     */
    public DlgDaftarPaket(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        tabMode=new DefaultTableModel(null,new String[]{
             "Kode Produk", "Nama Produk","Biaya"
            
            }){
              @Override public boolean isCellEditable(int rowIndex, int colIndex){return false;}
        };
        tbList.setModel(tabMode);
        tbList.setPreferredScrollableViewportSize(new Dimension(800,800));
        tbList.setAutoResizeMode(JTable.AUTO_RESIZE_OFF);
        for (i = 0; i < 3; i++) {
            TableColumn column = tbList.getColumnModel().getColumn(i);
            if(i==0){
                column.setPreferredWidth(120);
            }else if(i==1){
                column.setPreferredWidth(250);
            }else if(i==2){
                column.setPreferredWidth(80);
            }
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        internalFrame1 = new widget.InternalFrame();
        panelBiasa1 = new widget.PanelBiasa();
        label1 = new widget.Label();
        TCari = new widget.TextBox();
        button1 = new widget.Button();
        panelisi21 = new widget.panelisi2();
        button3 = new widget.Button();
        jScrollPane1 = new javax.swing.JScrollPane();
        tbList = new widget.Table();
        panelBiasa2 = new widget.PanelBiasa();
        label2 = new widget.Label();
        NoRwt = new widget.TextBox();
        panelisi1 = new widget.panelisi();
        label3 = new widget.Label();
        NmPasien = new widget.TextBox();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setUndecorated(true);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });

        internalFrame1.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createEtchedBorder(), "..:: Daftar Paket ::..", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("sansserif", 0, 11))); // NOI18N
        internalFrame1.setLayout(new java.awt.BorderLayout());

        label1.setText("Cari");
        label1.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        panelBiasa1.add(label1);

        TCari.setPreferredSize(new java.awt.Dimension(250, 24));
        TCari.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                TCariKeyPressed(evt);
            }
        });
        panelBiasa1.add(TCari);

        button1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/picture/accept.png"))); // NOI18N
        button1.setPreferredSize(new java.awt.Dimension(35, 32));
        button1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                button1ActionPerformed(evt);
            }
        });
        panelBiasa1.add(button1);

        panelisi21.setPreferredSize(new java.awt.Dimension(300, 25));

        javax.swing.GroupLayout panelisi21Layout = new javax.swing.GroupLayout(panelisi21);
        panelisi21.setLayout(panelisi21Layout);
        panelisi21Layout.setHorizontalGroup(
            panelisi21Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 298, Short.MAX_VALUE)
        );
        panelisi21Layout.setVerticalGroup(
            panelisi21Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 23, Short.MAX_VALUE)
        );

        panelBiasa1.add(panelisi21);

        button3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/picture/101.png"))); // NOI18N
        button3.setText("Keluar");
        button3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                button3ActionPerformed(evt);
            }
        });
        panelBiasa1.add(button3);

        internalFrame1.add(panelBiasa1, java.awt.BorderLayout.PAGE_END);

        tbList.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {

            }
        ));
        tbList.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                tbListKeyPressed(evt);
            }
        });
        jScrollPane1.setViewportView(tbList);

        internalFrame1.add(jScrollPane1, java.awt.BorderLayout.CENTER);

        label2.setText("No Rawat");
        label2.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        panelBiasa2.add(label2);

        NoRwt.setPreferredSize(new java.awt.Dimension(150, 24));
        panelBiasa2.add(NoRwt);

        panelisi1.setPreferredSize(new java.awt.Dimension(80, 24));

        javax.swing.GroupLayout panelisi1Layout = new javax.swing.GroupLayout(panelisi1);
        panelisi1.setLayout(panelisi1Layout);
        panelisi1Layout.setHorizontalGroup(
            panelisi1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 78, Short.MAX_VALUE)
        );
        panelisi1Layout.setVerticalGroup(
            panelisi1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 22, Short.MAX_VALUE)
        );

        panelBiasa2.add(panelisi1);

        label3.setText("Nama Pasien");
        label3.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        panelBiasa2.add(label3);

        NmPasien.setPreferredSize(new java.awt.Dimension(250, 24));
        panelBiasa2.add(NmPasien);

        internalFrame1.add(panelBiasa2, java.awt.BorderLayout.PAGE_START);

        getContentPane().add(internalFrame1, java.awt.BorderLayout.CENTER);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    
    private void cari(){
         try{
           ps= koneksi.prepareStatement("select kd_periksa,nm_periksa,harga from jns_perawatan_paket WHERE nm_periksa LIKE ?");
           ps.setString(1, "%"+TCari.getText()+"%");
           rs=ps.executeQuery();
           tabMode.setRowCount(0);
           while(rs.next()){
               tabMode.addRow(new Object[]{
               rs.getString("kd_periksa"),rs.getString("nm_periksa"),rs.getString("harga")
               });
           }
       }catch(Exception e){
           System.out.println("Error List Periksa : "+e.getMessage());
       }
    }
    
    private void tampil(){
         try{
           ps= koneksi.prepareStatement("select kd_periksa,nm_periksa,harga from jns_perawatan_paket");
           rs=ps.executeQuery();
           tabMode.setRowCount(0);
           while(rs.next()){
               tabMode.addRow(new Object[]{
               rs.getString("kd_periksa"),rs.getString("nm_periksa"),rs.getString("harga")
               });
           }
       }catch(Exception e){
           System.out.println("Error List Periksa : "+e.getMessage());
       }
    }
    
    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
      tampil();
    }//GEN-LAST:event_formWindowOpened

    private void TCariKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_TCariKeyPressed
        if(evt.getKeyCode()==KeyEvent.VK_ENTER){
            cari();
        }
    }//GEN-LAST:event_TCariKeyPressed

    private void button3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_button3ActionPerformed
        dispose();
    }//GEN-LAST:event_button3ActionPerformed
    
    public void setNo(String norwt, String nama){
        NoRwt.setText(norwt);
        NmPasien.setText(nama);
    }
    
    private void tbListKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_tbListKeyPressed
        if(evt.getKeyCode()==KeyEvent.VK_SPACE){
            
        }
    }//GEN-LAST:event_tbListKeyPressed

    private void button1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_button1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_button1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(DlgDaftarPaket.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(DlgDaftarPaket.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(DlgDaftarPaket.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(DlgDaftarPaket.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                DlgDaftarPaket dialog = new DlgDaftarPaket(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private widget.TextBox NmPasien;
    private widget.TextBox NoRwt;
    private widget.TextBox TCari;
    private widget.Button button1;
    private widget.Button button3;
    private widget.InternalFrame internalFrame1;
    private javax.swing.JScrollPane jScrollPane1;
    private widget.Label label1;
    private widget.Label label2;
    private widget.Label label3;
    private widget.PanelBiasa panelBiasa1;
    private widget.PanelBiasa panelBiasa2;
    private widget.panelisi panelisi1;
    private widget.panelisi2 panelisi21;
    private widget.Table tbList;
    // End of variables declaration//GEN-END:variables
}
