/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JDialog.java to edit this template
 */
package simrskhanza;
import fungsi.WarnaTable;
import fungsi.batasInput;
import fungsi.koneksiDB;
import fungsi.sekuel;
import fungsi.validasi;
import fungsi.akses;
import java.awt.Cursor;
import java.awt.Desktop;
import java.util.Date;
import java.awt.Dimension;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.text.DateFormat;
import java.text.SimpleDateFormat;
import java.time.Instant;
import java.util.Calendar;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
/**
 *
 * @author jónï ïNdÖ
 */
public class DlgResJatuh extends javax.swing.JDialog {
        private Connection koneksi=koneksiDB.condb();
        private sekuel Sequel=new sekuel();
        private PreparedStatement ps,ps2;
        private ResultSet rs,rs2;
        private int total,skor1,skor2,skor3,skor4,skor5,skor6,skor7,skor8,skor9;
    /**
     * Creates new form DlgResJatuh
     */
    public DlgResJatuh(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        
    
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        internalFrame1 = new widget.InternalFrame();
        jPanel1 = new javax.swing.JPanel();
        label1 = new widget.Label();
        txNoRW = new widget.TextBox();
        txNmPas = new widget.TextBox();
        label2 = new widget.Label();
        label3 = new widget.Label();
        txNoRM = new widget.TextBox();
        jLabel11 = new javax.swing.JLabel();
        jLabel47 = new javax.swing.JLabel();
        jLabel48 = new javax.swing.JLabel();
        cbTgl = new widget.Tanggal();
        cbShift = new javax.swing.JComboBox<>();
        jLabel12 = new javax.swing.JLabel();
        txJK = new widget.TextBox();
        jLabel14 = new javax.swing.JLabel();
        txTglLhr = new widget.TextBox();
        TglMsk = new widget.TextBox();
        jTabbedPane1 = new javax.swing.JTabbedPane();
        spIsian2 = new javax.swing.JScrollPane();
        PnIsian3 = new javax.swing.JPanel();
        jLabel35 = new javax.swing.JLabel();
        cbUsia3 = new javax.swing.JComboBox<>();
        jLabel36 = new javax.swing.JLabel();
        cbMental3 = new javax.swing.JComboBox<>();
        jLabel37 = new javax.swing.JLabel();
        cbEliminasi3 = new javax.swing.JComboBox<>();
        jLabel38 = new javax.swing.JLabel();
        cbObat3 = new javax.swing.JComboBox<>();
        jLabel39 = new javax.swing.JLabel();
        cbDiagnosis3 = new javax.swing.JComboBox<>();
        jLabel40 = new javax.swing.JLabel();
        cbAmbulasi3 = new javax.swing.JComboBox<>();
        jLabel41 = new javax.swing.JLabel();
        cbNutrisi3 = new javax.swing.JComboBox<>();
        jLabel42 = new javax.swing.JLabel();
        cbGT3 = new javax.swing.JComboBox<>();
        jLabel43 = new javax.swing.JLabel();
        cbRwytJatuh3 = new javax.swing.JComboBox<>();
        jLabel44 = new javax.swing.JLabel();
        lbTotal = new javax.swing.JLabel();
        scrollPane1 = new widget.ScrollPane();
        jPanel3 = new javax.swing.JPanel();
        jLabel13 = new javax.swing.JLabel();
        jPanel4 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tbIntv = new javax.swing.JTable();
        cb9 = new javax.swing.JCheckBox();
        cb5 = new javax.swing.JCheckBox();
        cb10 = new javax.swing.JCheckBox();
        cb11 = new javax.swing.JCheckBox();
        cb2 = new javax.swing.JCheckBox();
        cb3 = new javax.swing.JCheckBox();
        cb7 = new javax.swing.JCheckBox();
        cb6 = new javax.swing.JCheckBox();
        cb8 = new javax.swing.JCheckBox();
        cb1 = new javax.swing.JCheckBox();
        cb4 = new javax.swing.JCheckBox();
        btHapus = new widget.Button();
        jPanel2 = new javax.swing.JPanel();
        button1 = new widget.Button();
        button2 = new widget.Button();
        button3 = new widget.Button();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        internalFrame1.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));

        label1.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        label1.setText("No. Rawat");
        label1.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N

        label2.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        label2.setText("Nama Pasien");
        label2.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N

        label3.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        label3.setText("No RM");
        label3.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N

        jLabel11.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel11.setText("Tgl Masuk");

        jLabel47.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel47.setText("Shift");

        jLabel48.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel48.setText("Tanggal Input");

        cbShift.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Pagi", "Siang", "Malam" }));

        jLabel12.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel12.setText("Jenis Kelamin");

        txJK.setMaximumSize(new java.awt.Dimension(157, 157));

        jLabel14.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel14.setText("Tgl Lahir");

        txTglLhr.setMaximumSize(new java.awt.Dimension(157, 157));

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(31, 31, 31)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(label3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(txNoRM, javax.swing.GroupLayout.PREFERRED_SIZE, 155, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                        .addComponent(label1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(txNoRW, javax.swing.GroupLayout.PREFERRED_SIZE, 155, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                        .addComponent(label2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(txNmPas, javax.swing.GroupLayout.PREFERRED_SIZE, 155, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(52, 52, 52)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel48)
                    .addComponent(jLabel47)
                    .addComponent(jLabel11))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(cbShift, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(cbTgl, javax.swing.GroupLayout.DEFAULT_SIZE, 155, Short.MAX_VALUE)
                    .addComponent(TglMsk, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(33, 33, 33)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel12)
                    .addComponent(jLabel14))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txTglLhr, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(txJK, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel11)
                            .addComponent(txJK, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel12)
                            .addComponent(TglMsk, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(cbShift, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(txTglLhr, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jLabel14))
                            .addComponent(jLabel47, javax.swing.GroupLayout.Alignment.TRAILING))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel48)
                            .addComponent(cbTgl, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(label1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txNoRW, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(label2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txNmPas, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(label3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txNoRM, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jTabbedPane1.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        jLabel35.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel35.setText("1. USIA");

        cbUsia3.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "<50 Tahun", "50-79 Tahun", ">80 Tahun" }));
        cbUsia3.addPopupMenuListener(new javax.swing.event.PopupMenuListener() {
            public void popupMenuCanceled(javax.swing.event.PopupMenuEvent evt) {
            }
            public void popupMenuWillBecomeInvisible(javax.swing.event.PopupMenuEvent evt) {
                cbUsia3PopupMenuWillBecomeInvisible(evt);
            }
            public void popupMenuWillBecomeVisible(javax.swing.event.PopupMenuEvent evt) {
            }
        });
        cbUsia3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                cbUsia3MousePressed(evt);
            }
        });

        jLabel36.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel36.setText("2. STATUS MENTAL");

        cbMental3.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Sadar Penuh / Orientasi baik setiap saat", "Agitasi/Cemas", "Kadang Bingung", "Bingun/Disorientasi" }));
        cbMental3.addPopupMenuListener(new javax.swing.event.PopupMenuListener() {
            public void popupMenuCanceled(javax.swing.event.PopupMenuEvent evt) {
            }
            public void popupMenuWillBecomeInvisible(javax.swing.event.PopupMenuEvent evt) {
                cbMental3PopupMenuWillBecomeInvisible(evt);
            }
            public void popupMenuWillBecomeVisible(javax.swing.event.PopupMenuEvent evt) {
            }
        });

        jLabel37.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel37.setText("3. ELIMINASI");

        cbEliminasi3.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Mandiri & Mampu mengontrol BAB/BAK", "Kateter/Kolostomi", "Eliminasi dengan bantuan", "Gangguan Eliminasi", "Inkontinensia tapi mampu bergerak sendiri" }));
        cbEliminasi3.addPopupMenuListener(new javax.swing.event.PopupMenuListener() {
            public void popupMenuCanceled(javax.swing.event.PopupMenuEvent evt) {
            }
            public void popupMenuWillBecomeInvisible(javax.swing.event.PopupMenuEvent evt) {
                cbEliminasi3PopupMenuWillBecomeInvisible(evt);
            }
            public void popupMenuWillBecomeVisible(javax.swing.event.PopupMenuEvent evt) {
            }
        });

        jLabel38.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel38.setText("4. OBAT");

        cbObat3.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Tanpa Obat-obatan", "Obat Jantung", "Obat psikotropik(termasuk benzodiazepin, Antidepresan)", "Mendapat tambahan obat-obatan dan atau obat-obatan PRN yang diberikan dalam 24 Jam terakhir" }));
        cbObat3.addPopupMenuListener(new javax.swing.event.PopupMenuListener() {
            public void popupMenuCanceled(javax.swing.event.PopupMenuEvent evt) {
            }
            public void popupMenuWillBecomeInvisible(javax.swing.event.PopupMenuEvent evt) {
                cbObat3PopupMenuWillBecomeInvisible(evt);
            }
            public void popupMenuWillBecomeVisible(javax.swing.event.PopupMenuEvent evt) {
            }
        });

        jLabel39.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel39.setText("5. DIAGNOSIS");

        cbDiagnosis3.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Gangguan bipolar/Skizoafektif", "Gangguan penyalahgunaan zat/alkohol", "Gangguan Depresi Mayor", "Delirium/Demensia" }));
        cbDiagnosis3.addPopupMenuListener(new javax.swing.event.PopupMenuListener() {
            public void popupMenuCanceled(javax.swing.event.PopupMenuEvent evt) {
            }
            public void popupMenuWillBecomeInvisible(javax.swing.event.PopupMenuEvent evt) {
                cbDiagnosis3PopupMenuWillBecomeInvisible(evt);
            }
            public void popupMenuWillBecomeVisible(javax.swing.event.PopupMenuEvent evt) {
            }
        });

        jLabel40.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel40.setText("6. AMBULASI / KESEIMBANGAN");

        cbAmbulasi3.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Mandiri/langkah mantap", "Menggunakan alat bantuan (kursi roda, Walker)", "Vertigo", "Langkah tidak mantap/membutuhkan bantuan/sadar akan ketidakmampuannya", "Langkah tidak mantap, namun tidak menyadari keterbatasannya" }));
        cbAmbulasi3.addPopupMenuListener(new javax.swing.event.PopupMenuListener() {
            public void popupMenuCanceled(javax.swing.event.PopupMenuEvent evt) {
            }
            public void popupMenuWillBecomeInvisible(javax.swing.event.PopupMenuEvent evt) {
                cbAmbulasi3PopupMenuWillBecomeInvisible(evt);
            }
            public void popupMenuWillBecomeVisible(javax.swing.event.PopupMenuEvent evt) {
            }
        });

        jLabel41.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel41.setText("7. NUTRISI");

        cbNutrisi3.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Asuhan makan dan cairan dalam 24 jam terakhir sangat sedikit", "Tidak ada gangguan nafsu makan" }));
        cbNutrisi3.addPopupMenuListener(new javax.swing.event.PopupMenuListener() {
            public void popupMenuCanceled(javax.swing.event.PopupMenuEvent evt) {
            }
            public void popupMenuWillBecomeInvisible(javax.swing.event.PopupMenuEvent evt) {
                cbNutrisi3PopupMenuWillBecomeInvisible(evt);
            }
            public void popupMenuWillBecomeVisible(javax.swing.event.PopupMenuEvent evt) {
            }
        });

        jLabel42.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel42.setText("8. GANGGUAN TIDUR");

        cbGT3.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Tidak ada gangguan tidur", "Ada gangguan tidur yang dilaporkan oleh pasien, keluarga & petugas" }));
        cbGT3.addPopupMenuListener(new javax.swing.event.PopupMenuListener() {
            public void popupMenuCanceled(javax.swing.event.PopupMenuEvent evt) {
            }
            public void popupMenuWillBecomeInvisible(javax.swing.event.PopupMenuEvent evt) {
                cbGT3PopupMenuWillBecomeInvisible(evt);
            }
            public void popupMenuWillBecomeVisible(javax.swing.event.PopupMenuEvent evt) {
            }
        });

        jLabel43.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel43.setText("9. RIWAYAT JATUH");

        cbRwytJatuh3.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Tidak ada riwayat jatuh", "Riwayat jatuh dalam 3 bulan terakhir" }));
        cbRwytJatuh3.addPopupMenuListener(new javax.swing.event.PopupMenuListener() {
            public void popupMenuCanceled(javax.swing.event.PopupMenuEvent evt) {
            }
            public void popupMenuWillBecomeInvisible(javax.swing.event.PopupMenuEvent evt) {
                cbRwytJatuh3PopupMenuWillBecomeInvisible(evt);
            }
            public void popupMenuWillBecomeVisible(javax.swing.event.PopupMenuEvent evt) {
            }
        });

        jLabel44.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel44.setText("TOTAL SKOR");

        lbTotal.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        lbTotal.setForeground(new java.awt.Color(255, 0, 0));
        lbTotal.setText("0");

        javax.swing.GroupLayout PnIsian3Layout = new javax.swing.GroupLayout(PnIsian3);
        PnIsian3.setLayout(PnIsian3Layout);
        PnIsian3Layout.setHorizontalGroup(
            PnIsian3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PnIsian3Layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addGroup(PnIsian3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(PnIsian3Layout.createSequentialGroup()
                        .addGroup(PnIsian3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel36)
                            .addComponent(jLabel35))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 80, Short.MAX_VALUE)
                        .addGroup(PnIsian3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(cbUsia3, javax.swing.GroupLayout.PREFERRED_SIZE, 135, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(cbMental3, javax.swing.GroupLayout.PREFERRED_SIZE, 221, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(PnIsian3Layout.createSequentialGroup()
                        .addGroup(PnIsian3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel37)
                            .addComponent(jLabel38)
                            .addComponent(jLabel39)
                            .addComponent(jLabel40)
                            .addComponent(jLabel41)
                            .addComponent(jLabel42)
                            .addComponent(jLabel43)
                            .addComponent(jLabel44))
                        .addGap(14, 14, 14)
                        .addGroup(PnIsian3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(cbDiagnosis3, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(cbObat3, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(cbEliminasi3, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(cbAmbulasi3, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(cbNutrisi3, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(cbGT3, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(cbRwytJatuh3, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(lbTotal, javax.swing.GroupLayout.DEFAULT_SIZE, 221, Short.MAX_VALUE))))
                .addContainerGap(649, Short.MAX_VALUE))
        );
        PnIsian3Layout.setVerticalGroup(
            PnIsian3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PnIsian3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(PnIsian3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel35)
                    .addComponent(cbUsia3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(PnIsian3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel36)
                    .addComponent(cbMental3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(6, 6, 6)
                .addGroup(PnIsian3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cbEliminasi3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel37))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(PnIsian3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel38)
                    .addComponent(cbObat3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(PnIsian3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel39)
                    .addComponent(cbDiagnosis3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(PnIsian3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel40)
                    .addComponent(cbAmbulasi3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(PnIsian3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel41)
                    .addComponent(cbNutrisi3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(PnIsian3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel42)
                    .addComponent(cbGT3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(PnIsian3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel43)
                    .addComponent(cbRwytJatuh3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(PnIsian3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel44)
                    .addComponent(lbTotal))
                .addContainerGap(217, Short.MAX_VALUE))
        );

        spIsian2.setViewportView(PnIsian3);

        jTabbedPane1.addTab("PENILAIAN SKOR RESIKO JATUH", spIsian2);

        jPanel3.setBackground(new java.awt.Color(255, 255, 255));

        jLabel13.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel13.setText("LANGKAH - LANGKAH PENCEGAHAN PASIEN JATUH");

        tbIntv.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "ID", "Data yang dipilih"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(tbIntv);
        if (tbIntv.getColumnModel().getColumnCount() > 0) {
            tbIntv.getColumnModel().getColumn(0).setMinWidth(25);
            tbIntv.getColumnModel().getColumn(0).setPreferredWidth(45);
            tbIntv.getColumnModel().getColumn(0).setMaxWidth(45);
            tbIntv.getColumnModel().getColumn(1).setMinWidth(200);
            tbIntv.getColumnModel().getColumn(1).setPreferredWidth(450);
            tbIntv.getColumnModel().getColumn(1).setMaxWidth(450);
        }

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 608, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(14, Short.MAX_VALUE))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 182, Short.MAX_VALUE)
                .addContainerGap())
        );

        cb9.setBackground(new java.awt.Color(255, 255, 255));
        cb9.setText("Beritahukan efek anestesi kepada pasien / keluarga");
        cb9.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                cb9MousePressed(evt);
            }
        });

        cb5.setBackground(new java.awt.Color(255, 255, 255));
        cb5.setText("Bantu pasien saat transfer / ambulans");
        cb5.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                cb5MousePressed(evt);
            }
        });

        cb10.setBackground(new java.awt.Color(255, 255, 255));
        cb10.setText("Beritahukan orientasi ruangan kepada pasien / keluarga");
        cb10.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                cb10MousePressed(evt);
            }
        });

        cb11.setBackground(new java.awt.Color(255, 255, 255));
        cb11.setText("Atur pencahayaan di kamar pasien cukup / adekuat");
        cb11.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                cb11MousePressed(evt);
            }
        });

        cb2.setBackground(new java.awt.Color(255, 255, 255));
        cb2.setText("Tempatkan benda-benda milik pasien di dekat pasien");
        cb2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                cb2MousePressed(evt);
            }
        });

        cb3.setBackground(new java.awt.Color(255, 255, 255));
        cb3.setText("Pastikan tempat tidur dalam posisi rendah & roda terkunci");
        cb3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                cb3MousePressed(evt);
            }
        });

        cb7.setBackground(new java.awt.Color(255, 255, 255));
        cb7.setText("Bantu pasien ke kamar kecil secara teratur dan segera");
        cb7.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                cb7MousePressed(evt);
            }
        });

        cb6.setBackground(new java.awt.Color(255, 255, 255));
        cb6.setText("Pasangkan pengaman sisi tempat tidur");
        cb6.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                cb6MousePressed(evt);
            }
        });

        cb8.setBackground(new java.awt.Color(255, 255, 255));
        cb8.setText("Pasangkan tali pengaman bila perlu");
        cb8.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                cb8MousePressed(evt);
            }
        });

        cb1.setBackground(new java.awt.Color(255, 255, 255));
        cb1.setText("Sarankan untuk meminta bantuan ");
        cb1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                cb1MousePressed(evt);
            }
        });

        cb4.setBackground(new java.awt.Color(255, 255, 255));
        cb4.setText("Pastikan celana panjang & sarung pasien di atas mata kaki");
        cb4.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                cb4MousePressed(evt);
            }
        });
        cb4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cb4ActionPerformed(evt);
            }
        });

        btHapus.setText("Hapus");
        btHapus.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btHapusActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(24, 24, 24)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(cb9)
                            .addComponent(cb8)
                            .addComponent(cb7)
                            .addComponent(cb4)
                            .addComponent(cb3)
                            .addComponent(cb2)
                            .addComponent(cb1)
                            .addComponent(cb5)
                            .addComponent(cb6)
                            .addComponent(cb11)
                            .addComponent(cb10))
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addGap(28, 28, 28)
                                .addComponent(btHapus, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addGap(18, 18, 18)
                                .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addComponent(jLabel13))
                .addContainerGap(31, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addComponent(jLabel13)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(cb1)
                        .addGap(2, 2, 2)
                        .addComponent(cb2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(cb3)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(cb4)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(cb5)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(cb6)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(cb7)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(cb8)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(cb9)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(cb10)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(cb11))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(5, 5, 5)
                        .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(btHapus, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(290, Short.MAX_VALUE))
        );

        scrollPane1.setViewportView(jPanel3);

        jTabbedPane1.addTab("INTERVENSI", scrollPane1);

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));
        jPanel2.setForeground(new java.awt.Color(255, 255, 255));

        button1.setText("Simpan");
        button1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                button1ActionPerformed(evt);
            }
        });

        button2.setText("Baru");

        button3.setText("Ganti");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addComponent(button1, javax.swing.GroupLayout.PREFERRED_SIZE, 61, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(32, 32, 32)
                .addComponent(button2, javax.swing.GroupLayout.PREFERRED_SIZE, 61, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(button3, javax.swing.GroupLayout.PREFERRED_SIZE, 61, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(638, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                .addComponent(button1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addComponent(button2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addComponent(button3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        javax.swing.GroupLayout internalFrame1Layout = new javax.swing.GroupLayout(internalFrame1);
        internalFrame1.setLayout(internalFrame1Layout);
        internalFrame1Layout.setHorizontalGroup(
            internalFrame1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(internalFrame1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(internalFrame1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jTabbedPane1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 859, Short.MAX_VALUE)
                    .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        internalFrame1Layout.setVerticalGroup(
            internalFrame1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(internalFrame1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jTabbedPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 369, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(51, 51, 51))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(internalFrame1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(internalFrame1, javax.swing.GroupLayout.PREFERRED_SIZE, 544, Short.MAX_VALUE)
        );

        internalFrame1.getAccessibleContext().setAccessibleName("::[ Penilaian Resiko Jatuh Edmonson Psikiatri ]::");

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void cb4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cb4ActionPerformed
        // TODO add your handling code here:
                // TODO add your handling code here:
        
    }//GEN-LAST:event_cb4ActionPerformed

    private void cbUsia3MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_cbUsia3MousePressed

    }//GEN-LAST:event_cbUsia3MousePressed

    private void cbUsia3PopupMenuWillBecomeInvisible(javax.swing.event.PopupMenuEvent evt) {//GEN-FIRST:event_cbUsia3PopupMenuWillBecomeInvisible
        // TODO add your handling code here:
        if (cbUsia3.getSelectedIndex()==0){
          skor1 = 8;
        }else if (cbUsia3.getSelectedIndex()==1){
            skor1 = 10;
        }else if (cbUsia3.getSelectedIndex()==2){
            skor2 = 16;
        }   
    }//GEN-LAST:event_cbUsia3PopupMenuWillBecomeInvisible

    private void cbMental3PopupMenuWillBecomeInvisible(javax.swing.event.PopupMenuEvent evt) {//GEN-FIRST:event_cbMental3PopupMenuWillBecomeInvisible
        // TODO add your handling code here:
         if (cbMental3.getSelectedIndex()==0){
          skor2 = 4;
        }else if (cbMental3.getSelectedIndex()==1){
            skor2 = 12;
        }else if (cbMental3.getSelectedIndex()==2){
            skor2 = 13;
        }else if (cbMental3.getSelectedIndex()==3){
            skor2 = 14;
        }
    }//GEN-LAST:event_cbMental3PopupMenuWillBecomeInvisible

    private void cbEliminasi3PopupMenuWillBecomeInvisible(javax.swing.event.PopupMenuEvent evt) {//GEN-FIRST:event_cbEliminasi3PopupMenuWillBecomeInvisible
        if (cbEliminasi3.getSelectedIndex()==0){
          skor3 = 8;
        }else if (cbEliminasi3.getSelectedIndex()==1){
            skor3 = 12;
        }else if (cbEliminasi3.getSelectedIndex()==2){
            skor3 = 10;
        }else if (cbEliminasi3.getSelectedIndex()==3){
            skor3 = 12;
        }else if (cbEliminasi3.getSelectedIndex()==4){
            skor3 = 12;
        }
    }//GEN-LAST:event_cbEliminasi3PopupMenuWillBecomeInvisible

    private void cbObat3PopupMenuWillBecomeInvisible(javax.swing.event.PopupMenuEvent evt) {//GEN-FIRST:event_cbObat3PopupMenuWillBecomeInvisible
        // TODO add your handling code here:
        if (cbObat3.getSelectedIndex()==0){
          skor4 = 10;
        }else if (cbObat3.getSelectedIndex()==1){
            skor4 = 10;
        }else if (cbObat3.getSelectedIndex()==2){
            skor4 = 8;
        }else if (cbObat3.getSelectedIndex()==3){
            skor4 = 12;
        }
    }//GEN-LAST:event_cbObat3PopupMenuWillBecomeInvisible

    private void cbDiagnosis3PopupMenuWillBecomeInvisible(javax.swing.event.PopupMenuEvent evt) {//GEN-FIRST:event_cbDiagnosis3PopupMenuWillBecomeInvisible
        // TODO add your handling code here:
        if (cbDiagnosis3.getSelectedIndex()==0){
          skor5 = 10;
        }else if (cbDiagnosis3.getSelectedIndex()==1){
            skor5 = 10;
        }else if (cbDiagnosis3.getSelectedIndex()==2){
            skor5 = 8;
        }else if (cbDiagnosis3.getSelectedIndex()==3){
            skor5 = 12;
        }
    }//GEN-LAST:event_cbDiagnosis3PopupMenuWillBecomeInvisible

    private void cbAmbulasi3PopupMenuWillBecomeInvisible(javax.swing.event.PopupMenuEvent evt) {//GEN-FIRST:event_cbAmbulasi3PopupMenuWillBecomeInvisible
        // TODO add your handling code here:
        if (cbAmbulasi3.getSelectedIndex()==0){
          skor6 = 7;
        }else if (cbAmbulasi3.getSelectedIndex()==1){
            skor6 = 8;
        }else if (cbAmbulasi3.getSelectedIndex()==2){
            skor6 = 10;
        }else if (cbAmbulasi3.getSelectedIndex()==3){
            skor6 = 8;
        }else if (cbAmbulasi3.getSelectedIndex()==3){
            skor6 = 15;
        }
    }//GEN-LAST:event_cbAmbulasi3PopupMenuWillBecomeInvisible

    private void cbNutrisi3PopupMenuWillBecomeInvisible(javax.swing.event.PopupMenuEvent evt) {//GEN-FIRST:event_cbNutrisi3PopupMenuWillBecomeInvisible
        // TODO add your handling code here:
        if (cbNutrisi3.getSelectedIndex()==0){
          skor7 = 12;
        }else if (cbNutrisi3.getSelectedIndex()==1){
            skor7 = 0;
        }
    }//GEN-LAST:event_cbNutrisi3PopupMenuWillBecomeInvisible

    private void cbGT3PopupMenuWillBecomeInvisible(javax.swing.event.PopupMenuEvent evt) {//GEN-FIRST:event_cbGT3PopupMenuWillBecomeInvisible
        // TODO add your handling code here:
        if (cbGT3.getSelectedIndex()==0){
          skor8 = 8;
        }else if (cbGT3.getSelectedIndex()==1){
            skor8 = 12;
        }
    }//GEN-LAST:event_cbGT3PopupMenuWillBecomeInvisible

    private void cbRwytJatuh3PopupMenuWillBecomeInvisible(javax.swing.event.PopupMenuEvent evt) {//GEN-FIRST:event_cbRwytJatuh3PopupMenuWillBecomeInvisible
        // TODO add your handling code here:
        if (cbRwytJatuh3.getSelectedIndex()==0){
          skor9 = 8;
        }else if (cbRwytJatuh3.getSelectedIndex()==1){
            skor9 = 14;
        }
        total = skor1+skor2+skor3+skor4+skor5+skor6+skor7+skor8+skor9;
        if (total<90){
            lbTotal.setText("Tidak beresiko(-). Nilai ="+Integer.toString(total));
        }else if(total>90){
            lbTotal.setText("Beresiko Jatuh(+). Nilai ="+Integer.toString(total));
        }
        
    }//GEN-LAST:event_cbRwytJatuh3PopupMenuWillBecomeInvisible

    private void HpsPilih(int kol, int id){
    DefaultTableModel model = (DefaultTableModel)tbIntv.getModel();
    for(int i = 0; i < model.getRowCount(); i++){
        if (model.getValueAt(i, kol).equals(id)){ 
         model.removeRow(i);
            }        
        }
    }
    private void isPilih(String id){
        if(cb1.isSelected()==false){
        DefaultTableModel model = (DefaultTableModel)tbIntv.getModel();
        for(int i=model.getRowCount() -1; i>=0; i--){
        }
        model.addRow(new String[]{id,cb1.getText()});
        }
    }
    private void cb1MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_cb1MousePressed
        // TODO add your handling code here:
        if (cb1.isSelected()==true){
        HpsPilih(0,0);
        }else if(cb1.isSelected()==false){
        isPilih("0");
        }
    }//GEN-LAST:event_cb1MousePressed

    private void btHapusActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btHapusActionPerformed
        // TODO add your handling code here:
        DefaultTableModel model = (DefaultTableModel)tbIntv.getModel();
        if (tbIntv.getValueAt(tbIntv.getSelectedRow(), 0).equals("0")) {
          cb1.setSelected(false);
          model.removeRow(tbIntv.getSelectedRow());
        }else if (tbIntv.getValueAt(tbIntv.getSelectedRow(), 0).equals("1")) {
          cb2.setSelected(false);
          model.removeRow(tbIntv.getSelectedRow());
        }else if (tbIntv.getValueAt(tbIntv.getSelectedRow(), 0).equals("2")) {
          cb3.setSelected(false);
          model.removeRow(tbIntv.getSelectedRow());
        }else if (tbIntv.getValueAt(tbIntv.getSelectedRow(), 0).equals("3")) {
          cb4.setSelected(false);
          model.removeRow(tbIntv.getSelectedRow());
        }else if (tbIntv.getValueAt(tbIntv.getSelectedRow(), 0).equals("4")) {
          cb5.setSelected(false);
          model.removeRow(tbIntv.getSelectedRow());
        }else if (tbIntv.getValueAt(tbIntv.getSelectedRow(), 0).equals("5")) {
          cb6.setSelected(false);
          model.removeRow(tbIntv.getSelectedRow());
        }else if (tbIntv.getValueAt(tbIntv.getSelectedRow(), 0).equals("6")) {
          cb7.setSelected(false);
          model.removeRow(tbIntv.getSelectedRow());
        }else if (tbIntv.getValueAt(tbIntv.getSelectedRow(), 0).equals("7")) {
          cb8.setSelected(false);
          model.removeRow(tbIntv.getSelectedRow());
        }else if (tbIntv.getValueAt(tbIntv.getSelectedRow(), 0).equals("8")) {
          cb9.setSelected(false);
          model.removeRow(tbIntv.getSelectedRow());
        }else if (tbIntv.getValueAt(tbIntv.getSelectedRow(), 0).equals("9")) {
          cb10.setSelected(false);
          model.removeRow(tbIntv.getSelectedRow());
        }else if (tbIntv.getValueAt(tbIntv.getSelectedRow(), 0).equals("10")) {
          cb11.setSelected(false);
          model.removeRow(tbIntv.getSelectedRow());
        }
        
//        for(int i= model.getRowCount() -1; i>=0; i--){
//            model.removeRow(i);
//        }
    }//GEN-LAST:event_btHapusActionPerformed

    private void cb2MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_cb2MousePressed
        // TODO add your handling code here:
        if (cb2.isSelected()==true){
        HpsPilih(0,1);
        }else if(cb2.isSelected()==false){
        DefaultTableModel model = (DefaultTableModel)tbIntv.getModel();
        model.addRow(new String[]{"1",cb2.getText()});
        }
        
    }//GEN-LAST:event_cb2MousePressed

    private void cb3MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_cb3MousePressed
        // TODO add your handling code here:
        if (cb3.isSelected()==true){
        HpsPilih(0,1);
        }else if(cb3.isSelected()==false){
        DefaultTableModel model = (DefaultTableModel)tbIntv.getModel();
        model.addRow(new String[]{"2",cb3.getText()});
        }
    }//GEN-LAST:event_cb3MousePressed

    private void cb4MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_cb4MousePressed
        // TODO add your handling code here:
        if (cb4.isSelected()==true){
        HpsPilih(0,1);
        }else if(cb4.isSelected()==false){
        DefaultTableModel model = (DefaultTableModel)tbIntv.getModel();
        model.addRow(new String[]{"3",cb4.getText()});
        }
    }//GEN-LAST:event_cb4MousePressed

    private void cb5MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_cb5MousePressed
        // TODO add your handling code here:
        if (cb5.isSelected()==true){
        HpsPilih(0,1);
        }else if(cb5.isSelected()==false){
        DefaultTableModel model = (DefaultTableModel)tbIntv.getModel();
        model.addRow(new String[]{"4",cb5.getText()});
        }
    }//GEN-LAST:event_cb5MousePressed

    private void cb6MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_cb6MousePressed
        // TODO add your handling code here:
        if (cb6.isSelected()==true){
        HpsPilih(0,1);
        }else if(cb6.isSelected()==false){
        DefaultTableModel model = (DefaultTableModel)tbIntv.getModel();
        model.addRow(new String[]{"5",cb6.getText()});
        }
    }//GEN-LAST:event_cb6MousePressed

    private void cb7MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_cb7MousePressed
        // TODO add your handling code here:
        if (cb7.isSelected()==true){
        HpsPilih(0,1);
        }else if(cb7.isSelected()==false){
        DefaultTableModel model = (DefaultTableModel)tbIntv.getModel();
        model.addRow(new String[]{"6",cb7.getText()});
        }
    }//GEN-LAST:event_cb7MousePressed

    private void cb8MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_cb8MousePressed
        // TODO add your handling code here:
        if (cb8.isSelected()==true){
        HpsPilih(0,1);
        }else if(cb8.isSelected()==false){
        DefaultTableModel model = (DefaultTableModel)tbIntv.getModel();
        model.addRow(new String[]{"7",cb8.getText()});
        }
    }//GEN-LAST:event_cb8MousePressed

    private void cb9MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_cb9MousePressed
        // TODO add your handling code here:
        if (cb9.isSelected()==true){
        HpsPilih(0,1);
        }else if(cb9.isSelected()==false){
        DefaultTableModel model = (DefaultTableModel)tbIntv.getModel();
        model.addRow(new String[]{"8",cb9.getText()});
        }
    }//GEN-LAST:event_cb9MousePressed

    private void cb10MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_cb10MousePressed
        // TODO add your handling code here:
        if (cb10.isSelected()==true){
        HpsPilih(0,1);
        }else if(cb10.isSelected()==false){
        DefaultTableModel model = (DefaultTableModel)tbIntv.getModel();
        model.addRow(new String[]{"9",cb10.getText()});
        }
    }//GEN-LAST:event_cb10MousePressed

    private void cb11MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_cb11MousePressed
        // TODO add your handling code here:
        if (cb11.isSelected()==true){
        HpsPilih(0,1);
        }else if(cb11.isSelected()==false){
        DefaultTableModel model = (DefaultTableModel)tbIntv.getModel();
        model.addRow(new String[]{"10",cb11.getText()});
        }
    }//GEN-LAST:event_cb11MousePressed

    private void button1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_button1ActionPerformed
            try {
                DateFormat tgl = new SimpleDateFormat("yyyy-MM-dd");
                Calendar Kal = Calendar.getInstance();
                DateFormat jam = new SimpleDateFormat("HH:mm:ss");
                
                String tglK = tgl.format(cbTgl.getDate());
                ps2 = koneksi.prepareStatement("SELECT ifnull(max(x1),0) as hsl FROM penilaian_edmonson");
                rs = ps2.executeQuery();
                rs.next();              
                int hasil = Integer.parseInt(rs.getString("hsl"))+1;
                
                // TODO add your handling code here:
                ps =  koneksi.prepareStatement("insert into penilaian_edmonson values(?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?)");
            ps.setString(1, txNoRW.getText());
            ps.setString(2, Integer.toString(hasil));
            ps.setString(3, txNoRM.getText());
            ps.setString(4, cbShift.getSelectedItem().toString());
            ps.setString(5, tglK);
            ps.setString(6, jam.format(Kal.getTime()));
            if (cb1.isSelected()){
            ps.setString(7, "true");
            }else{
                ps.setString(7, "false");
            }
            if (cb2.isSelected()){
            ps.setString(8, "true");
            }else{
                ps.setString(8, "false");
            }
            if (cb3.isSelected()){
            ps.setString(9, "true");
            }else{
                ps.setString(9, "false");
            }
            if (cb4.isSelected()){
            ps.setString(10, "true");
            }else{
                ps.setString(10, "false");
            }
            if (cb5.isSelected()){
            ps.setString(11, "true");
            }else{
                ps.setString(11, "false");
            }
            if (cb6.isSelected()){
            ps.setString(12, "true");
            }else{
                ps.setString(12, "false");
            }
            if (cb7.isSelected()){
            ps.setString(13, "true");
            }else{
                ps.setString(13, "false");
            }
            if (cb8.isSelected()){
            ps.setString(14, "true");
            }else{
                ps.setString(14, "false");
            }
            if (cb9.isSelected()){
            ps.setString(15, "true");
            }else{
                ps.setString(15, "false");
            }
            if (cb10.isSelected()){
            ps.setString(16, "true");
            }else{
                ps.setString(16, "false");
            }
            if (cb11.isSelected()){
            ps.setString(17, "true");
            }else{
                ps.setString(17, "false");
            }
            
            ps.setString(18, cbUsia3.getSelectedItem().toString());
            ps.setString(19, cbMental3.getSelectedItem().toString());
            ps.setString(20, cbEliminasi3.getSelectedItem().toString());
            ps.setString(21, cbObat3.getSelectedItem().toString());
            ps.setString(22, cbDiagnosis3.getSelectedItem().toString());
            ps.setString(23, cbAmbulasi3.getSelectedItem().toString());
            ps.setString(24, cbNutrisi3.getSelectedItem().toString());
            ps.setString(25, cbGT3.getSelectedItem().toString());
            ps.setString(26, cbRwytJatuh3.getSelectedItem().toString());
            ps.setString(27, "12345");
            ps.setString(28, lbTotal.getText());
            ps.executeUpdate();
            
//            if (ps.>0){
//                System.out.println("Notif : Sukses");
//            }
            } catch (SQLException ex) {
                System.out.println("Notif :"+ex.getMessage());
            }
        
    }//GEN-LAST:event_button1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(DlgResJatuh.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(DlgResJatuh.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(DlgResJatuh.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(DlgResJatuh.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                DlgResJatuh dialog = new DlgResJatuh(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel PnIsian3;
    private widget.TextBox TglMsk;
    private widget.Button btHapus;
    private widget.Button button1;
    private widget.Button button2;
    private widget.Button button3;
    private javax.swing.JCheckBox cb1;
    private javax.swing.JCheckBox cb10;
    private javax.swing.JCheckBox cb11;
    private javax.swing.JCheckBox cb2;
    private javax.swing.JCheckBox cb3;
    private javax.swing.JCheckBox cb4;
    private javax.swing.JCheckBox cb5;
    private javax.swing.JCheckBox cb6;
    private javax.swing.JCheckBox cb7;
    private javax.swing.JCheckBox cb8;
    private javax.swing.JCheckBox cb9;
    private javax.swing.JComboBox<String> cbAmbulasi3;
    private javax.swing.JComboBox<String> cbDiagnosis3;
    private javax.swing.JComboBox<String> cbEliminasi3;
    private javax.swing.JComboBox<String> cbGT3;
    private javax.swing.JComboBox<String> cbMental3;
    private javax.swing.JComboBox<String> cbNutrisi3;
    private javax.swing.JComboBox<String> cbObat3;
    private javax.swing.JComboBox<String> cbRwytJatuh3;
    private javax.swing.JComboBox<String> cbShift;
    private widget.Tanggal cbTgl;
    private javax.swing.JComboBox<String> cbUsia3;
    private widget.InternalFrame internalFrame1;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel35;
    private javax.swing.JLabel jLabel36;
    private javax.swing.JLabel jLabel37;
    private javax.swing.JLabel jLabel38;
    private javax.swing.JLabel jLabel39;
    private javax.swing.JLabel jLabel40;
    private javax.swing.JLabel jLabel41;
    private javax.swing.JLabel jLabel42;
    private javax.swing.JLabel jLabel43;
    private javax.swing.JLabel jLabel44;
    private javax.swing.JLabel jLabel47;
    private javax.swing.JLabel jLabel48;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTabbedPane jTabbedPane1;
    private widget.Label label1;
    private widget.Label label2;
    private widget.Label label3;
    private javax.swing.JLabel lbTotal;
    private widget.ScrollPane scrollPane1;
    private javax.swing.JScrollPane spIsian2;
    private javax.swing.JTable tbIntv;
    private widget.TextBox txJK;
    private widget.TextBox txNmPas;
    private widget.TextBox txNoRM;
    private widget.TextBox txNoRW;
    private widget.TextBox txTglLhr;
    // End of variables declaration//GEN-END:variables

    
public void setNoRm(String norwt, Date tgl2, String nmpas) {
       
        txNoRW.setText(norwt);
        Sequel.cariIsi("select reg_periksa.tgl_registrasi from reg_periksa where reg_periksa.no_rawat='"+norwt+"'", TglMsk);
        cbTgl.setDate(tgl2);
        txNmPas.setText(nmpas);
        isRawat();
        isPsien();
//        ChkInput.setSelected(true);
//        isForm();
    }

private void isRawat() {
         Sequel.cariIsi("select reg_periksa.no_rkm_medis from reg_periksa where reg_periksa.no_rawat='"+txNoRW.getText()+"' ", txNoRM);
    }
private void isPsien() {
        try {
            ps=koneksi.prepareStatement("select pasien.nm_pasien,pasien.jk,date_format(pasien.tgl_lahir,'%d-%m-%Y') as lahir from pasien where pasien.no_rkm_medis=?");
            try {
                ps.setString(1,txNoRM.getText());
                rs=ps.executeQuery();
                if(rs.next()){
                    txNmPas.setText(rs.getString("nm_pasien"));
                    txJK.setText(rs.getString("jk"));
                    if (txJK.getText().equals("L")){
                        txJK.setText("Laki-laki");
                    }else if (txJK.getText().equals("P")){
                        txJK.setText("Perempuan");
                    }                   
                    txTglLhr.setText(rs.getString("lahir"));
                }
            } catch (Exception e) {
                System.out.println("Notif : "+e);
            }finally {
                if(rs!=null){
                    rs.close();
                }
                if(ps!=null){
                    ps.close();
                }
            }
        } catch (Exception e) {
            System.out.println("Notif : "+e);
        }
    }
}