/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JDialog.java to edit this template
 */
package simrskhanza;

import fungsi.koneksiDB;
import fungsi.sekuel;
import fungsi.validasi;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.text.SimpleDateFormat;
import java.util.Calendar;

/**
 *
 * @author firka
 */
public class DlgTransNonPasien extends javax.swing.JDialog {
private ResultSet rs;
private validasi Valid = new validasi();
private sekuel sequel = new sekuel();
private Connection koneksi = koneksiDB.condb();
private PreparedStatement ps;
private String NULL;
private String dateStamp = new SimpleDateFormat("yyyy-MM-dd").format(Calendar.getInstance().getTime());
private String timeStamp = new SimpleDateFormat("HH:mm:ss").format(Calendar.getInstance().getTime());
    /**
     * Creates new form DlgTransNonPasien
     */
    public DlgTransNonPasien(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        internalFrame1 = new widget.InternalFrame();
        tabPane1 = new widget.TabPane();
        scrollPane1 = new widget.ScrollPane();
        panelGray3 = new widget.PanelGray();
        label13 = new widget.Label();
        label14 = new widget.Label();
        textBox9 = new widget.TextBox();
        textBox10 = new widget.TextBox();
        label15 = new widget.Label();
        jScrollPane3 = new javax.swing.JScrollPane();
        txAlamat = new widget.TextArea();
        label16 = new widget.Label();
        textBox11 = new widget.TextBox();
        button5 = new widget.Button();
        label17 = new widget.Label();
        textBox12 = new widget.TextBox();
        button6 = new widget.Button();
        jScrollPane4 = new javax.swing.JScrollPane();
        txKet = new widget.TextArea();
        label18 = new widget.Label();
        jScrollPane5 = new javax.swing.JScrollPane();
        tbTrans = new widget.Table();
        scrollPane2 = new widget.ScrollPane();
        panelGray2 = new widget.PanelGray();
        button9 = new widget.Button();
        button10 = new widget.Button();
        button11 = new widget.Button();
        button12 = new widget.Button();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        internalFrame1.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createEtchedBorder(), "..:: Transaksi Non Pasien ::..", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("sansserif", 0, 11))); // NOI18N
        internalFrame1.setLayout(new java.awt.BorderLayout());

        panelGray3.setLayout(null);

        label13.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        label13.setText("No Transaksi");
        panelGray3.add(label13);
        label13.setBounds(10, 20, 70, 20);

        label14.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        label14.setText("Atas Nama");
        panelGray3.add(label14);
        label14.setBounds(10, 50, 60, 20);
        panelGray3.add(textBox9);
        textBox9.setBounds(80, 50, 150, 24);
        panelGray3.add(textBox10);
        textBox10.setBounds(80, 20, 150, 24);

        label15.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        label15.setText("Alamat");
        panelGray3.add(label15);
        label15.setBounds(10, 80, 60, 20);

        txAlamat.setColumns(20);
        txAlamat.setRows(5);
        jScrollPane3.setViewportView(txAlamat);

        panelGray3.add(jScrollPane3);
        jScrollPane3.setBounds(80, 80, 250, 60);

        label16.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        label16.setText("Unit");
        panelGray3.add(label16);
        label16.setBounds(370, 20, 60, 20);
        panelGray3.add(textBox11);
        textBox11.setBounds(440, 20, 150, 24);

        button5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/picture/190.png"))); // NOI18N
        panelGray3.add(button5);
        button5.setBounds(590, 20, 30, 30);

        label17.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        label17.setText("Pelaksana");
        panelGray3.add(label17);
        label17.setBounds(370, 50, 60, 20);
        panelGray3.add(textBox12);
        textBox12.setBounds(440, 50, 150, 24);

        button6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/picture/190.png"))); // NOI18N
        panelGray3.add(button6);
        button6.setBounds(590, 50, 30, 30);

        txKet.setColumns(20);
        txKet.setRows(5);
        jScrollPane4.setViewportView(txKet);

        panelGray3.add(jScrollPane4);
        jScrollPane4.setBounds(440, 80, 250, 60);

        label18.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        label18.setText("Keterangan");
        panelGray3.add(label18);
        label18.setBounds(370, 80, 60, 20);

        tbTrans.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {

            }
        ));
        jScrollPane5.setViewportView(tbTrans);

        panelGray3.add(jScrollPane5);
        jScrollPane5.setBounds(0, 160, 800, 170);

        scrollPane1.setViewportView(panelGray3);

        tabPane1.addTab("Transaksi Non Pasien", scrollPane1);
        tabPane1.addTab("List Transaksi", scrollPane2);

        internalFrame1.add(tabPane1, java.awt.BorderLayout.CENTER);

        button9.setIcon(new javax.swing.ImageIcon(getClass().getResource("/picture/129.png"))); // NOI18N
        button9.setText("Tindakan");
        panelGray2.add(button9);

        button10.setIcon(new javax.swing.ImageIcon(getClass().getResource("/picture/Cancel-2-16x16.png"))); // NOI18N
        button10.setText("Hapus");
        panelGray2.add(button10);

        button11.setIcon(new javax.swing.ImageIcon(getClass().getResource("/picture/095.png"))); // NOI18N
        button11.setText("Simpan");
        panelGray2.add(button11);

        button12.setIcon(new javax.swing.ImageIcon(getClass().getResource("/picture/101.png"))); // NOI18N
        button12.setText("Keluar");
        panelGray2.add(button12);

        internalFrame1.add(panelGray2, java.awt.BorderLayout.PAGE_END);

        getContentPane().add(internalFrame1, java.awt.BorderLayout.CENTER);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(DlgTransNonPasien.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(DlgTransNonPasien.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(DlgTransNonPasien.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(DlgTransNonPasien.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                DlgTransNonPasien dialog = new DlgTransNonPasien(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private widget.Button button1;
    private widget.Button button10;
    private widget.Button button11;
    private widget.Button button12;
    private widget.Button button2;
    private widget.Button button3;
    private widget.Button button4;
    private widget.Button button5;
    private widget.Button button6;
    private widget.Button button9;
    private widget.ComboBox comboBox1;
    private widget.ComboBox comboBox2;
    private widget.InternalFrame internalFrame1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JScrollPane jScrollPane5;
    private widget.Label label1;
    private widget.Label label10;
    private widget.Label label11;
    private widget.Label label12;
    private widget.Label label13;
    private widget.Label label14;
    private widget.Label label15;
    private widget.Label label16;
    private widget.Label label17;
    private widget.Label label18;
    private widget.Label label2;
    private widget.Label label3;
    private widget.Label label4;
    private widget.Label label5;
    private widget.Label label6;
    private widget.Label label7;
    private widget.Label label8;
    private widget.Label label9;
    private widget.PanelGray panelGray1;
    private widget.PanelGray panelGray2;
    private widget.PanelGray panelGray3;
    private widget.PanelGray panelGray4;
    private widget.ScrollPane scrollPane1;
    private widget.ScrollPane scrollPane2;
    private widget.TabPane tabPane1;
    private widget.Table tbTrans;
    private widget.TextArea textArea1;
    private widget.TextArea textArea2;
    private widget.TextBox textBox1;
    private widget.TextBox textBox10;
    private widget.TextBox textBox11;
    private widget.TextBox textBox12;
    private widget.TextBox textBox2;
    private widget.TextBox textBox3;
    private widget.TextBox textBox4;
    private widget.TextBox textBox5;
    private widget.TextBox textBox6;
    private widget.TextBox textBox7;
    private widget.TextBox textBox8;
    private widget.TextBox textBox9;
    private widget.TextArea txAlamat;
    private widget.TextArea txKet;
    // End of variables declaration//GEN-END:variables
}
